### ISSUE TITLE
react native canvas can only be 300 by 150

### ISSUE THREAD

**Issue by bobmandude9889** [iddan/react-native-canvas#100]
https://github.com/iddan/react-native-canvas/blob/ba3f2e9a53010dd10e538e8169f9937de7b770a4/src/Canvas.js#L13

**Comment by iddan** [comment]
Thanks for giving React Native Canvas a try. To change the dimensions of the canvas just set it's height and weight properties.
For example:
```javascript
canvas.height = 500;
canvas.width = 1000;
```

**Comment by llGaetanll** [comment]
This answer does not really help...
When resizing the canvas, nothing can be drawn to it
```JS
handleCanvas = (canvas) => {
    this.c = canvas.getContext('2d');
    canvas.height = Dimensions.get('window').height;
    canvas.width = Dimensions.get('window').width;
    
    this.c.beginPath();
    this.c.arc(100, 200, 100, 0, 2*Math.PI);
    this.c.stroke();
  }
```
^^^ Although the canvas does get resized, this does not draw anything.
```JS
handleCanvas = (canvas) => {
    this.c = canvas.getContext('2d');
    // canvas.height = Dimensions.get('window').height;
    // canvas.width = Dimensions.get('window').width;
    
    this.c.beginPath();
    this.c.arc(100, 200, 100, 0, 2*Math.PI);
    this.c.stroke();
  }
```
^^^ This draws just fine

Not sure what to do about it

Could you provide an example please?
thank you so much!

**Comment by kapilgorve** [comment]
I did changed the size before getting context and it worked fine. Just spent last 2-3 hours untill I saw this issue. I thought there was something wrong with my positioning values. Anyway here you go.

`   canvas.width = wheelSize;
    canvas.height = wheelSize;
    const ctx = canvas.getContext('2d');
`

**Comment by pramodkumar005** [comment]
If I set custom height and width of canvas it's not showing any shape  
 handleCanvas = (canvas) =>{
     canvas.width = 200;
    canvas.height = 200;
    const context = canvas.getContext('2d');
    context.fillStyle = 'purple';
    context.fillRect(0, 0, 100, 100);
  }
When i remove canvas custom height and width the shape is visible
handleCanvas = (canvas) =>{
     //canvas.width = 200;
    //canvas.height = 200;
    const context = canvas.getContext('2d');
    context.fillStyle = 'purple';
    context.fillRect(0, 0, 100, 100);
  }

Render :
render(){
      return (
        <View style={{flex:1}}>
          <Canvas ref={this.handleCanvas} />       

        </View>
      );
  }

Any suggestion what am i doing wrong ?

**Comment by Leslie-Wong-H** [comment]
> I did changed the size before getting context and it worked fine. Just spent last 2-3 hours untill I saw this issue. I thought there was something wrong with my positioning values. Anyway here you go.
> 
> ` canvas.width = wheelSize; canvas.height = wheelSize; const ctx = canvas.getContext('2d');`

For those who use the useRef hook, here is a similar solution.
```js
        // @ts-ignore
        canvas.current.width = width;
        // @ts-ignore
        canvas.current.height = height;
        let ctx = (canvas as React.MutableRefObject<Canvas>).current.getContext(
          "2d"
        );
```
