### ISSUE TITLE
How to get continuous mouse position

### ISSUE THREAD

**Issue by J-Cake** [iddan/react-native-canvas#104]
Hi, I want to implement a drawing app using this module, the question is, I can't seem to find any docs on reading the mouse position as it moves on screen, how can I do that?

I figured since it's based on a HTML canvas, there might be a solution there, but that requires adding an event listener to it, and I don't believe that's possible, correct me if I'm wrong, please!

**Comment by iddan** [comment]
For responsiveness it is better to use React Native's API for listening to mouses and gestures than relying on the WebView as sending messages from the WebView is slow.

**Comment by KlaussMC** [comment]
@iddan Hi, thanks for the response, I've found the docs on `react-native-gesture-responder` and that seems to be what I'm looking for, and as you suggested, it's native
