### ISSUE TITLE
NSURLErrorDomain in Expo 32 (specifically)

### ISSUE THREAD

**Issue by pahakrai** [iddan/react-native-canvas#106]
![image](https://user-images.githubusercontent.com/6316520/51381211-7a9cb480-1b4e-11e9-973b-fe766fa9c909.png)

![image](https://user-images.githubusercontent.com/6316520/51381273-af107080-1b4e-11e9-9e16-13093be10b79.png)
Error whenever canvas is used even the repo example

**Comment by Billmike** [comment]
Is there a fix for this issue yet? 😢

**Comment by iddan** [comment]
Is it occurring only on Expo?

**Comment by iddan** [comment]
Seem like an issue with Expo

**Comment by kensmash** [comment]
Hard to tell. Wondering if it's an issue with the way Expo interacts with React Native Canvas? Maybe there's a fix that can be applied to Canvas that would allow users to upgrade to the latest Expo SDK?

**Comment by iddan** [comment]
Might be but I have no clue as I've never used Expo and unfamiliar with it's internals. PRs are welcome though.

**Comment by iddan** [comment]
Can you check with the new version?

**Comment by kensmash** [comment]
To test, I created a fresh install of React Native with Expo (expo init) and added react-native-canvas and nothing else. Now when I preview the app, I see this error: 
![img_0892](https://user-images.githubusercontent.com/29924723/52962529-77722f80-336b-11e9-9a34-dee03ab53668.png)

Here are my dependencies:
![screen shot 2019-02-18 at 10 50 41 am](https://user-images.githubusercontent.com/29924723/52962554-848f1e80-336b-11e9-8f4e-984663894f20.png)

And lastly, the app code: https://gist.github.com/kensmash/6ec6cc32deed1cf24dfea4c886eb94c3

**Comment by iddan** [comment]
Thank you. I'll try to get that. If you manage to fix it a PR is welcome!

**Comment by iddan** [comment]
From: https://www.npmjs.com/package/react-native-webview
> Note: React Native WebView is not currently supported by Expo unless you "eject".
You will need to eject and let `react-native-webview` link in order to use this package.

**Comment by kensmash** [comment]
Oh man ok, thank you for the information.
