### ISSUE TITLE
Unable to resolve module 'react-native-webview'

### ISSUE THREAD

**Issue by dmaksimovic** [iddan/react-native-canvas#108]
Hi, I'm getting the error

`Unable to resolve module 'react-native-webview' from 'node_modules/react-native/canvas/dist/Canvas.js'`

...when running in Expo with the latest version. I used to have an older version but now I've upgraded and I'm getting this error.

I see that indeed in dist/Canvas.js this module is required on line 30, but the module is only declared in devDependencies. 

I also see there's been a recent commit to disable the warning by adding it to devDependencies, but if the library is really using it, then it must go to regular dependencies or peer-dependencies. For now I'll downgrade and see how it works.

**Comment by iddan** [comment]
I see. I'll fix that

**Comment by iddan** [comment]
Fixed in react-native-canvas@0.1.27
