### ISSUE TITLE
Canvas not displayed after updating to 0.1.26^

### ISSUE THREAD

**Issue by Randyhuls** [iddan/react-native-canvas#111]
After updating to 0.1.26  - which is dependent on the new WebView - the canvas doesn't seem to render in my application. Function calls seem to work properly, the Canvas component also exists in my app, but it's simply isn't displaying anything. I get zero errors and my code runs fine; it seems to be pure visually.

The update is paired with a warning:
`The scalesPageToFit property is not supported when useWebKit = true`

I am using 0.1.25 for now, but unfortunately that also produces  a warning about the WebView being extracted from core. Would appreciate any help! Thanks!

**Comment by iddan** [comment]
Hey, thanks for reporting in such detail. Let me see what can I do.

**Comment by ionut-movila** [comment]
I can confirm this problem. Going back to version 0.1.25 does show the canvas.

**Comment by iddan** [comment]
Can you check 0.1.28?

**Comment by ionut-movila** [comment]
IMO the problem is not related to `scalesPageToFit`. That is just a warning. 

If I did open with Safari to inspect the webview of the canvas, in version using the new WebView from package `react-native-webview` the canvas doesn't have any size. It just shows as <canvas>. On version 0.1.25 it does have attributes height and width.

Must be something else. Like some broken bridge with the new webview?

**Comment by Randyhuls** [comment]
@iddan Thanks for the razor fast response! The warning is gone, but unfortunately the error persists. And I can confirm what ionut-movila is saying. The canvas element in Safari seems to have its default 320x150 size.

**Comment by iddan** [comment]
I'll try now to run and see

**Comment by iddan** [comment]
Okay, I've fixed all the compat problems with `react-native-webview`. It's a shame things doesn't work the same as before. Check out version 0.1.29

**Comment by iddan** [comment]
0.1.30 solves android as well.

**Comment by Randyhuls** [comment]
Thanks @iddan, works great now!
