### ISSUE TITLE
How to change color image local?

### ISSUE THREAD

**Issue by Hieutt1704** [iddan/react-native-canvas#112]
Can I change color for a image local with react-native canvas?

**Comment by iddan** [comment]
What is image local in this context? And what is to change color?

**Comment by Hieutt1704** [comment]
example: your avatar, can i change the wall color behind you?

**Comment by Tanatcu** [comment]
If I understand you correct, you should use getImageData for getting image data and manipulate this one.
As example use this answer
https://www.tutorialspoint.com/Change-colour-of-an-image-drawn-on-an-HTML5-canvas-element

**Comment by Hieutt1704** [comment]
I have a issues when i try to use getImageData:

![simulator screen shot - iphone x - 2019-03-01 at 23 07 47](https://user-images.githubusercontent.com/38338250/53650447-215c9080-3c77-11e9-8744-03ecd24ad8ba.png)

Here my code:
_componentDidMount() {
    const canvas = this.handleImageRect
    if (!canvas) return
    const image = new CanvasImage(canvas);
    canvas.width = 200;
    canvas.height = 200;
    const context = canvas.getContext('2d');
    image.src = 'https://upload.wikimedia.org/wikipedia/commons/6/63/Biho_Takashi._Bat_Before_the_Moon%2C_ca._1910.jpg';
    image.addEventListener('load', () => {
      context.drawImage(image, 0, 0)
    })
  }

  _changeImage() {
    const canvas = this.handleImageRect
    if (!canvas) return
    canvas.width = 200;
    canvas.height = 200;
    const context = canvas.getContext('2d');
    console.log(canvas, context)
    context.getImageData(0, 0, 200, 200)
      .then(imageData => {
        const data = Object.values(imageData.data);
        console.log(data)
      })
  }_

where am i wrong?

Thanks for help!!!  :grinning:

**Comment by Hieutt1704** [comment]
> I have a issue when i try to use getImageData:
> 
> ![simulator screen shot - iphone x - 2019-03-01 at 23 07 47](https://user-images.githubusercontent.com/38338250/53650447-215c9080-3c77-11e9-8744-03ecd24ad8ba.png)
> 
> Here my code:
> _componentDidMount() { const canvas = this.handleImageRect if (!canvas) return const image = new CanvasImage(canvas); canvas.width = 200; canvas.height = 200; const context = canvas.getContext('2d'); image.src = 'https://upload.wikimedia.org/wikipedia/commons/6/63/Biho_Takashi._Bat_Before_the_Moon%2C_ca._1910.jpg'; image.addEventListener('load', () => { context.drawImage(image, 0, 0) }) }_
> 
> _changeImage() { const canvas = this.handleImageRect if (!canvas) return canvas.width = 200; canvas.height = 200; const context = canvas.getContext('2d'); console.log(canvas, context) context.getImageData(0, 0, 200, 200) .then(imageData => { const data = Object.values(imageData.data); console.log(data) }) }_
> 
> where am i wrong?
> 
> Thanks for help!!! 😀
