### ISSUE TITLE
Images are not loading (with solution)

### ISSUE THREAD

**Issue by maximus123123** [iddan/react-native-canvas#114]
Solution: 
Just add originWhitelist to your canvas as its a prop for WebView

<Canvas originWhitelist={['https://*']}  ref={this.handlePath} />

Please @iddan this to the example

**Comment by iddan** [comment]
Accepting PRs

**Comment by maximus123123** [comment]
Will do :) great job by the way

Think we need more examples for things like local files, camera images etc to standardize the way people interact with CanvasImage component, don't you think?

**Comment by iddan** [comment]
For sure! Will accept those

**Comment by maximus123123** [comment]
I lie,
I'm getting tainted canvas with local images when trying to get the canvas as an image, no matter how I load the local images, external urls work fine.
Would also be nice to use require for local images instead of having to use file system which may solve that issue.

**Comment by maximus123123** [comment]
Image.resolveAssetSource works only locally, doesn't give the true uri in release version in android at least, also tried prepending file:///android_asset/ which sometimes works but get tainted canvas

**Comment by maximus123123** [comment]
On IOS, none of the images are working, drawing on canvas works but an image(local or url) with not fire the load listener

**Comment by maximus123123** [comment]
well due to my IQ being lower that a squirrel, I didn't notice my webview version being locked at 2.15
