### ISSUE TITLE
Error after installation RNCWebView

### ISSUE THREAD

**Issue by Adetiwa** [iddan/react-native-canvas#115]
Hello.
I keep getting this error

error: bundling failed: Error: Unable to resolve module `react-native-webview` from `...t/node_modules/react-native-canvas/dist/Canvas.js`: Module `react-native-webview` does not exist in the Haste module map

Was getting this initially 
Invariant Violation: requireNativeComponent: "RNCWebView" was not found in the UIManager

What do I do? Thanks.

I installed v0.1.30

**Comment by iddan** [comment]
Are you using Expo?

**Comment by Adetiwa** [comment]
No I’m not.

**Comment by iddan** [comment]
`yarn link`?

**Comment by Adetiwa** [comment]
Yes

**Comment by iddan** [comment]
Sound like a `react-native-webview` issue. Please share if you figure something out.

**Comment by Adetiwa** [comment]
Okay

**Comment by Tanatcu** [comment]
I had this issue today but library version update have fixed it.

**Comment by Husbin** [comment]
hi, i use expo and meet the same issue,how can i fixed it? thx.

**Comment by Alexey5791** [comment]
Hello, I have this issue using expo. What should i do?

**Comment by iddan** [comment]
Hey! You should use the `master` version of Expo or wait for them to release it.
