### ISSUE TITLE
Android: RNCWebView error message

### ISSUE THREAD

**Issue by MateRyze** [iddan/react-native-canvas#123]
When I navigate to the component, that uses Canvas I get the following error message:
> Invariant Violation: requireNativeComponent: "RNCWebView" was not found in the UIManager.
This error is located at:
    in RNCWebView (at WebView.android.js:215)
    in RCTView (at View.js:45)
    in View (at WebView.android.js:218)
    in WebView (at Canvas.js:129)
    in RCTView (at View.js:45)
    in View (at Canvas.js:128)
    in Canvas (at LapDetails.tsx:236)
    in RCTView (at View.js:45)
    in View (at LapDetails.tsx:277)
    in RCTView (at View.js:45)
    in View (at LapDetails.tsx:248)
    in LapDetails (at ComponentWrapper.js:29)
    in WrappedComponent (at renderApplication.js:34)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:33)
...

Some important dependencies:
    "react": "16.6.3",
    "react-native": "0.58.6",
    "react-native-canvas": "^0.1.31",
    "react-native-webview": "^5.4.2"

Tested with Android (API Level 28) emulator and physical device.

Linking of Webview with `$ react-native link react-native-webview` does not helped.

**Comment by NicholasEli** [comment]
What helped me was `npm install react-native-webview` then manually link it to my project

**Comment by MateRyze** [comment]
> What helped me was `npm install react-native-webview` then manually link it to my project

In my case it doesn't helped, but it works for a new react native project without other dependencies than `react-native-canvas `and `react-native-webview`.
I think the error could be caused by `react-native-navigation`...

**Comment by hugpeter** [comment]
> What helped me was `npm install react-native-webview` then manually link it to my project

Did you have to eject from Expo to add this?

**Comment by Pines-Cheng** [comment]
same question, under native React Native.

**Comment by V3RT1AG0** [comment]
I am running into the same issue. Not sure if it is because of React native navigation.

**Comment by bohehe** [comment]
the same problem. I had tried ways in [this issue](https://github.com/react-native-community/react-native-webview/issues/161) and ways in stackoverflow, nothing helps.
Both linking command and configing xcode library didn't work for me.

The npmjs react-native-webview says
```
If you're getting Invariant Violation: Native component for "RNCWKWebView does not exist" it likely means you forgot to run react-native link or there was some error with the linking process
```
So I'm sure there is sth wrong with the linking process.
But sadly, I can noy find anyway to solve this

**Comment by bohehe** [comment]
this issue solved my problem: [https://stackoverflow.com/questions/43311439/react-native-bvlineargradient-react-rctviewmanager-h-file-not-found?rq=1](https://stackoverflow.com/questions/43311439/react-native-bvlineargradient-react-rctviewmanager-h-file-not-found?rq=1)

**Comment by iddan** [comment]
Closing as this issue gone stale

**Comment by gun-ctrl** [comment]
Hi，Have you found the cause of the issue？
