### ISSUE TITLE
Android canvas scroll

### ISSUE THREAD

**Issue by sergey-kompaniets** [iddan/react-native-canvas#131]
How to remove top and bottom scroll style?
![photo5460742976755051101](https://user-images.githubusercontent.com/39048297/59029506-237e4e80-8867-11e9-99e4-2e4ba7978fb7.jpg)
![photo5460742976755051102](https://user-images.githubusercontent.com/39048297/59029507-237e4e80-8867-11e9-9fa5-317038ea3c90.jpg)

**Comment by iddan** [comment]
Closing as this issue gone stale. Unfortunately, I don't know how to help with it and I'm not sure it has to do with the component itself.
