### ISSUE TITLE
Copy contents from one canvas to another

### ISSUE THREAD

**Issue by VanessaChu** [iddan/react-native-canvas#132]
I noticed that every time I try to load the image to a canvas by setting canvas.src, the canvas  "blinks" (disappears and reappears when image is loaded) I'm trying to work around this by using a destination canvas and once all images have been drawn on the source canvas, copy it over to the destination canvas. Following a stackoverflow here: https://stackoverflow.com/questions/4405336/how-to-copy-contents-of-one-canvas-to-another-canvas-locally

I'm trying to do this:

`
//grab the context from your destination canvas
var destCtx = destinationCanvas.getContext('2d');

//call its drawImage() function passing it the source canvas directly
destCtx.drawImage(sourceCanvas, 0, 0);
`

but keep receiving Type error, converting circular object to JSON.

**Comment by iddan** [comment]
Hey, thank you for using React Native Canvas. I think an easier solution for you problem would be just to wait for all the images to load and then render them:
```javascript
const loadImage = (canvas, src) =>
    new Promise((resolve, reject) => {
        const image = new CanvasImage(canvas);
        image.src = src;
        image.addEventListener("load", () => resolve());
        image.addEventListener("error", reject);
    });

Promise.all([
    loadImage(canvas, 'src of image 1'),
    loadImage(canvas, 'src of image 2'),
]).then(images => {
    const [image1, image2] = images;
    ctx.drawImage(image1, 0, 0, 100, 100);
    ctx.drawImage(image2, 0, 0, 100, 100);
})
```
If this won't do you should you should use `getImageData()` and `putImageData()`

**Comment by iddan** [comment]
Closing as this issue has gone stale.

**Comment by James-Firth** [comment]
Hi @iddan I'd like to be able to copy using the same approach as Vanessa mentioned.

I'm trying to allow a user to draw on a masked region and need to be able to quickly isolate and modify that "layer". Since it's dynamic I don't think I can use the `CanvasImage` as I'm not loading an image.

The `getImageData` function is also too slow for what I'm doing as it creates a lot of lag.

Any ideas?
