### ISSUE TITLE
image must be initialized with a canvas instance

### ISSUE THREAD

**Issue by sergey-kompaniets** [iddan/react-native-canvas#133]
```jsx
<View
        onStartShouldSetResponder={() => true}
        onResponderStart={this.mouseDownListener}
        onResponderMove={this.mouseMoveListener}
        onResponderRelease={this.mouseUpListener}
        style={{
          // flexGrow: 1,
          height: canvasHeight,
          alignItems: "center",
          marginTop: (3 * h) / 100
        }}
      >
        
        <View>
          <View
            style={{
              height: canvasHeight,
              width: bgWidth
              // backgroundColor: "green"
            }}
          >
            <Image
              source={bgImg}
              style={{
                // flexGrow: 1,
                width: null,
                height: "100%"
              }}
              resizeMode="contain"
            />
          </View>
          <View
            style={{
              height: canvasHeight,
              width: bgWidth,
              position: "absolute",
              alignItems: "center"
            }}
          >
            <Canvas
              ref={this.handleCanvas}
              style={
                {
                  // backgroundColor: "red"
                }
              }
            />
          </View>
        </View>
      </View>
```

**Comment by iddan** [comment]
Make sure to create `CanvasImage` like:
```javascript
handleCanvas = canvas => {
    const image = new CanvasImage(canvas);
}
```

**Comment by sergey-kompaniets** [comment]
`handleCanvas = canvas => {
    const { canvasHeight, canvasWidth, imgSrc } = this.props;

    const image = new CanvasImage(canvas);

    canvas.height = canvasHeight;
    canvas.width = canvasWidth;
    const ctx = canvas.getContext("2d");
    const rectX = 0;
    const rectY = 0;
    const rectWidth = canvasWidth;
    const rectHeight = canvasHeight;

    ctx.lineJoin = "round";

    image.src = `${RNFS.MainBundlePath}/assets/${imgSrc}`;

    image.addEventListener(
      "load",
      (drawImageCanvas = () => {
        ctx.drawImage(image, rectX, rectY, rectWidth, rectHeight);
      })
    );

    this.setState({ canvas: canvas });
  };`

**Comment by sergey-kompaniets** [comment]
This error show me after Actions.pop()

**Comment by sergey-kompaniets** [comment]
> Make sure to create `CanvasImage` like:
> 
> ```js
> handleCanvas = canvas => {
>     const image = new CanvasImage(canvas);
> }
> ```

This error show me after Actions.pop() or replace

**Comment by sergey-kompaniets** [comment]
@iddan, please help!

**Comment by iddan** [comment]
`removeEventListener()` is not implemented currently

**Comment by sergey-kompaniets** [comment]
how can I fixed this problem?

**Comment by sergey-kompaniets** [comment]
@iddan, please, I need help

**Comment by iddan** [comment]
You can implement it if you'd like: take a look at how `addEventListener()` is implemented.

**Comment by neohuiji** [comment]
Hi, @iddan, I alse have this problem.  I got `Error: Image must be initialized with a Canvas instance`. 
Here is my code :
```
import Canvas, { Image as CanvasImage } from 'react-native-canvas';
import RNFS from 'react-native-fs';


    const _handleCanvas = (canvas) => {
        const image = new CanvasImage(canvas);
        canvas.width = 500;
        canvas.height = 500;
        image.src = `${RNFS.MainBundlePath}/${viewerData[0].path}`;
        console.log('image src: ', image.src);
        // the log here is  `undefined/../../images/3.jpg`
        const context = canvas.getContext('2d');
        image.addEventListener('load', () => {
            context.drawImage(image, 0, 0, 500, 500);
        });
    };

    return ( 
      <View>
            <Canvas ref={_handleCanvas} />
      </View>
)

```

**Comment by iddan** [comment]
Needs investigation. Currently, I'm not available.

**Comment by kaidoj** [comment]
Works like this.
```js
<Canvas ref={(canvas) => this.handleCanvas(canvas)} />
```

**Comment by kaidoj** [comment]
Canvas is not initialized when calling new CanvasImage. Something to do with render method of react-native. Seems solved problem with little workaround.  Checking if canvas is set.
```js
handleCanvas = (canvas) => {
    if (!(canvas instanceof Canvas)) {
      return;
    }

    const image = new CanvasImage(canvas);
```

**Comment by iddan** [comment]
Oh right, refs in React can be `null`. Make sure to check that before using a canvas instance!
