### ISSUE TITLE
putImageData is not working

### ISSUE THREAD

**Issue by arthuryeti** [iddan/react-native-canvas#136]
Hello,

I'm trying to replicate your example `handleImageData`, but got an error:

![IMAGE 2019-06-29 10:18:15](https://user-images.githubusercontent.com/849866/60381576-4ad7ce00-9a57-11e9-922c-059e7153cb29.jpg)

What do you think?

**Comment by arthuryeti** [comment]
Any ideas about this?

**Comment by iddan** [comment]
Closing as this issue gone stale.
