### ISSUE TITLE
getImageData cannot get text color on canvas for Android

### ISSUE THREAD

**Issue by sangium47** [iddan/react-native-canvas#138]
I was try to get color by using getImageData from canvas which included rectangle and text in the same canvas. The output of rectangle's color is fine, but not work with text. This issue is occur on Android only. IOS is fine.

Here's a code
```javascript
    const sendCtx = this.sendCanvas.getContext('2d')
    sendCtx.fillStyle = bgColor
    sendCtx.fillRect(0, 0, 64, 32)
    if (text.length > 0) {
      const _fontSize = fontSize / 5

      each(text, (t, i) => {
        const y =
          text.length > 1
            ? (32 / (text.length + 1)) * (i + 1) + 2.5
            : 16 + _fontSize / 2 - 1
        if (t !== undefined) {
          let x = 5
          if (t.align === 'center') x = 64 / 2
          if (t.align === 'right') x = 64 - 5
          sendCtx.fillStyle = textColor
          sendCtx.fillText(t.text, x, y)
        }
      })
    }

    const result = []
    for (let i = 0; i < 32; i++) {
      result[i] = []
      for (let j = 0; j < 64; j++) {
        const data = await sendCtx.getImageData(i, j, 1, 1)
        const _imageData = data.data
        result[i][j] = [_imageData[0], _imageData[1], _imageData[2]]
      }
    }
```

**Comment by iddan** [comment]
You might need to wait for text to render. Here is how:
```javascript
const sendCtx = this.sendCanvas.getContext('2d')
sendCtx.fillStyle = bgColor
sendCtx.fillRect(0, 0, 64, 32)
if (text.length > 0) {
    const _fontSize = fontSize / 5

    await Promise.all(text.map((t, i) => {
        const y =
            text.length > 1
            ? (32 / (text.length + 1)) * (i + 1) + 2.5
            : 16 + _fontSize / 2 - 1
        if (t !== undefined) {
            let x = 5
            if (t.align === 'center') x = 64 / 2
            if (t.align === 'right') x = 64 - 5
            sendCtx.fillStyle = textColor
            return sendCtx.fillText(t.text, x, y)
        }
    }))
}

const result = []
for (let i = 0; i < 32; i++) {
    result[i] = []
    for (let j = 0; j < 64; j++) {
    const data = await sendCtx.getImageData(i, j, 1, 1)
    const _imageData = data.data
    result[i][j] = [_imageData[0], _imageData[1], _imageData[2]]
    }
}
```

**Comment by sangium47** [comment]
> You might need to wait for text to render. Here is how:
> 
> ```js
> const sendCtx = this.sendCanvas.getContext('2d')
> sendCtx.fillStyle = bgColor
> sendCtx.fillRect(0, 0, 64, 32)
> if (text.length > 0) {
>     const _fontSize = fontSize / 5
> 
>     await Promise.all(text.map((t, i) => {
>         const y =
>             text.length > 1
>             ? (32 / (text.length + 1)) * (i + 1) + 2.5
>             : 16 + _fontSize / 2 - 1
>         if (t !== undefined) {
>             let x = 5
>             if (t.align === 'center') x = 64 / 2
>             if (t.align === 'right') x = 64 - 5
>             sendCtx.fillStyle = textColor
>             return sendCtx.fillText(t.text, x, y)
>         }
>     }))
> }
> 
> const result = []
> for (let i = 0; i < 32; i++) {
>     result[i] = []
>     for (let j = 0; j < 64; j++) {
>         const data = await sendCtx.getImageData(i, j, 1, 1)
>         const _imageData = data.data
>         result[i][j] = [_imageData[0], _imageData[1], _imageData[2]]
>     }
> }
> ```
> 
> Also for better performance, you should use `Promise.all` for getting ImageData as well:
> 
> ```js
> const getPixel = async (sendCtx, i, j) => {
>     const data = await sendCtx.getImageData(i, j, 1, 1)
>     const _imageData = data.data
>     const pixel = [_imageData[0], _imageData[1], _imageData[2]]
>     return [i, j, pixel]
> }
> 
> const pixelPromises = []
> for (let j = 0; j < 64; j++) {
>     pixelPromises.push(getPixel(sendCtx, i, j))
> }
> const result = []
> const pixels = await Promise.all(pixelPromises);
> for (const [i, j, pixel] of pixels) {
>     result[i] = []
>     result[i][j] = pixel;
> }
> ```

Thank you for your solution, but it's still not working in Android.

**Comment by iddan** [comment]
Closing as this issue has gone stale.
