### ISSUE TITLE
Typescript Error when Assigning Canvas to ref

### ISSUE THREAD

**Issue by RageBill** [iddan/react-native-canvas#148]
I was referring to an earlier solution to update the canvas on state change in [#76 comment](https://github.com/iddan/react-native-canvas/issues/76#issuecomment-417915694) and I encountered this error with Typescript:
```
TS2322: Type 'RefObject<Canvas>' is not assignable to type '(string & ((canvas: Canvas) => any)) | (RefObject<Canvas> & ((canvas: Canvas) => any)) | (((instance: Canvas | null) => void) & ((canvas: Canvas) => any))'.
  Type 'RefObject<Canvas>' is not assignable to type 'RefObject<Canvas> & ((canvas: Canvas) => any)'.
    Type 'RefObject<Canvas>' is not assignable to type '(canvas: Canvas) => any'.
      Type 'RefObject<Canvas>' provides no match for the signature '(canvas: Canvas): any'.
```

This basically means I cannot merely do `ref={this.canvas}` as suggested in the above link to the Canvas. Any good solution here to solve this issue?

My dependencies:
"react-native": "0.60.4"
"typescript": "3.5.3"
"@types/react-native-canvas": "0.1.1"
"react-native-canvas": "0.1.33"
"react-native-webview": "6.7.0"

**Comment by iddan** [comment]
Hey, I do not maintain the types of react-native-canvas but I'd love to review a PR that fixes it :)

**Comment by RageBill** [comment]
@iddan I have made a [pull request](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38120) for the types to fix this issue together with a few other errors I found. Please help review :)
