### ISSUE TITLE
react native 0.60 , react-native-community/react-native-webview

### ISSUE THREAD

**Issue by emdDevelop** [iddan/react-native-canvas#151]
Canvas is not showing --variant=release. Its working on development mode

**Comment by iddan** [comment]
Thank you for reporting. Any errors?

**Comment by emdDevelop** [comment]
no errors build is successful.

**Comment by emdDevelop** [comment]
on ./gradlew bundleRelease --warning-mode all 
this warning only
> Configure project :react-native-webview
The DefaultSourceDirectorySet constructor has been deprecated. This is scheduled to be removed in Gradle 6.0. Please use the ObjectFactory service to create instances of SourceDirectorySet instead.
        at build_
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)

**Comment by emdDevelop** [comment]
Finally  it has to do with react native map version. When i upgade to final version the problem is solved.
Working with this package json 
"dependencies": {
    "@mapbox/sphericalmercator": "^1.1.0",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/netinfo": "^4.2.1",
    "native-base": "^2.13.7",
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-canvas": "^0.1.34",
    "react-native-easy-grid": "^0.2.2",
    "react-native-maps": "0.26.1",
    "react-native-navigation": "^3.0.0-alpha.11",
    "react-native-webview": "^7.4.1",
    "react-redux": "^7.1.1",
    "redux": "^4.0.4",
    "redux-thunk": "^2.3.0"
  },

**Comment by iddan** [comment]
So can this issue be closed?

**Comment by emdDevelop** [comment]
yeap
