### ISSUE TITLE
doesn't work when using stack navigator (react navigation): null is not an object

### ISSUE THREAD

**Issue by KFernandoDilepix** [iddan/react-native-canvas#153]
When going back to the previous screen the app is crashing and I got this error: `TypeError: null is not an object (evaluating 'canvas.getContext')`.

Otherwise its drawing on the proper screen.

**Comment by iddan** [comment]
Hey, I think what you experience is a canvas ref nullified. Can you please add a check that canvas is not `null ` before your code and see if it fixes your problem?

**Comment by KFernandoDilepix** [comment]
Hello, its not working. I think the ref is null but I don't understand why ...

**Comment by KFernandoDilepix** [comment]
Here my code: `_handleCanvas = (canvas) => {
        const ctx = canvas.getContext('2d');
        ctx.fillStyle = 'purple';
        ctx.fillRect(0, 0, 100, 100);
    };

    _renderCanvas = () => {
        return <Canvas ref={this._handleCanvas}/>;
    };

    render() {

        return (
            <View style={styles.container}>
                <Text>Detection Screen</Text>
                {this._renderCanvas()}
            </View>
        );
    }`

**Comment by KFernandoDilepix** [comment]
Here my code: 
![Capture du 2019-10-12 19-27-12](https://user-images.githubusercontent.com/52405799/66705390-501b0900-ed26-11e9-86e0-543c72e6f726.png)

**Comment by kasback** [comment]
Hello, im experiencing the same issue, i think that at the moment canvas.getContext() gets called, the element isn't rendered yet ? note that after a refresh the error goes away and the canvas does work.

**Comment by kasback** [comment]
Hello i think this should fix your problem :
```
if (canvas !== null){
            const ctx = canvas.getContext('2d');
            canvas.width = 500;
            canvas.height = 500;
            ctx.beginPath();
            ctx.arc(170, 150, 100, 0, 2 * Math.PI);
           ctx.stroke();
}
```

**Comment by KFernandoDilepix** [comment]
@kasback I will try this. Thanks.

**Comment by KFernandoDilepix** [comment]
@kasback Indeed its working ! Thank you guys @iddan

**Comment by FarazzShaikh** [comment]
After implementing this solution, I’m still getting a TypeError as canvas ref is evaluated as undefined. This is weird because I am checking if the ref is truthy and the ref is still throwing an error.
