### ISSUE TITLE
Currently not working with Expo SDK 35?

### ISSUE THREAD

**Issue by SebLambla** [iddan/react-native-canvas#154]
Hi,

I've got an app based on Expo that uses react-native-canvas to place a picture on top of an other and then export the result with `.toDataURL()`.

Everything was working fine on Expo 30 but react-native-canvas doesn't seem to work with Expo 35. Here is the piece of code that I tried:

```
class App extends Component {
  handleCanvas = (canvas) => {
    const ctx = canvas.getContext('2d');
    ctx.fillStyle = 'purple';
    ctx.fillRect(0, 0, 100, 100);
  }
 
  render() {
    return (
      <Canvas ref={this.handleCanvas}/>
    )
  }
}
```

And my package.json :

```
"dependencies": {
    "expo": "^35.0.0",
    "react-native-canvas": "^0.1.23",
    "react-native-webview": "^7.4.2",
   ...
  }
```

Any help is greatly appreciated!

**Comment by iddan** [comment]
Hey, thank you for reporting. Are you using Expo web? I've seen there is an [issue](https://github.com/react-native-community/react-native-webview/issues/945) reported with Expo web and react-native-webview

**Comment by SebLambla** [comment]
Hi, nope it’s a mobile app.
I’ve also tried with Expo SDK 33, which doesn’t work neither.

**Comment by iddan** [comment]
Your `react-native-canvas` version is pretty old. Can you try `0.1.34`?

**Comment by SebLambla** [comment]
I created an [Expo Snack](https://snack.expo.io/@seblambla/react-native-canvas), that works on both SDK 33 and SDK 35. I guess the problem comes from my package.json. I'll get back to you when I find something relevant!

**Comment by SebLambla** [comment]
Everything seems ok with Expo SDK 35 and these versions:

```
    "react-native-canvas": "^0.1.34",
    "react-native-webview": "^7.0.5",
    ...
```

Thanks!
