### ISSUE TITLE
Cannot set property 'width' of null

### ISSUE THREAD

**Issue by wulala1997** [iddan/react-native-canvas#157]
componentlUnmount   error:Cannot set property 'width' of null

```javascript
  handleCanvas = (canvas) => {
    canvas.width = 100;
    canvas.height = 100;
    const context = canvas.getContext('2d');
    context.fillStyle = 'purple';
    context.fillRect(0, 0, 100, 100);
  }
```

**Comment by iddan** [comment]
Hey, thank you for giving React Native Canvas a try and reporting the issue.
I'm not sure I understand the error you reported:
Is the code you provided the code you are using?
Can you provide a screenshot?

**Comment by iddan** [comment]
Closing as no response was given
