### ISSUE TITLE
Drawing by on touch event

### ISSUE THREAD

**Issue by jvink** [iddan/react-native-canvas#159]
Hi there,

Is it possible to draw on the canvas using on touch events? The component does not seem to have those properties (onTouchStart), but I was wondering if you have some implementation or example.

Thanks!

**Comment by iddan** [comment]
Hello,
Yes, you can wrap the canvas with a [PanResponder](https://facebook.github.io/react-native/docs/panresponder) and use the events emitted from the component

**Comment by vikasacharya16** [comment]
> Hi there,
> 
> Is it possible to draw on the canvas using on touch events? The component does not seem to have those properties (onTouchStart), but I was wondering if you have some implementation or example.
> 
> Thanks!

hi do you have any example please

**Comment by neeraj-tangariya** [comment]
Hi @iddan, I want to know that I wraaped the canvas inside the view component, Now i want to restrict only draw inside the canvas not the outside of block how to handle this can you help us out.
![image](https://user-images.githubusercontent.com/118344444/236210203-5814c282-c153-40b3-bcbe-45ca5ace3eb7.png)
