### ISSUE TITLE
ctx.stroke() bad typing

### ISSUE THREAD

**Issue by luisgurmendezMLabs** [iddan/react-native-canvas#164]
If you are strictly following the CanvasRenderingContext2d api https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/stroke  the stroke function can be called with no path.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1cfa56bd636df485a2942a0bf1bb18f1ce1faf76/types/react-native-canvas/index.d.ts#L124

**Comment by iddan** [comment]
Cool, would love a PR
