### ISSUE TITLE
Crashes the app when using android9

### ISSUE THREAD

**Issue by ryanypm** [iddan/react-native-canvas#165]
This is the problem link for Webview
```
https://github.com/react-native-community/react-native-webview/issues/429
https://github.com/react-native-community/react-native-webview/issues/1069
```

When I added: ```opacity: 0.99``` to Webview, the problem was solved.

It is said that this problem is caused by the hardware acceleration of Android9. Can we use this hack? ```opacity: 0.99```

**Comment by iddan** [comment]
Pull requests are welcome

**Comment by iddan** [comment]
The hack should be done only when OS is Android 9

**Comment by ryanypm** [comment]
> The hack should be done only when OS is Android 9

I will leave the decision to the user, so I do n’t have to judge Android9, can I?

**Comment by ryanypm** [comment]
Tested not limited to Android 9
