### ISSUE TITLE
Doesn't work on iOS

### ISSUE THREAD

**Issue by vikjovanov** [iddan/react-native-canvas#173]
Hi !

when I use Canvas, it works perfectly on Android, however nothing is displayed on iOS!

What is this due to?

Here is this very simple code that I run:
```js
    handleCanvas = (canvas) => {
        if (canvas !== null){
            const ctx = canvas.getContext('2d');
            canvas.height = 500;
            ctx.fillRect(0,0, 40, 60);
        }
      }

    render() {
        return (
            <SafeAreaView>
                <Canvas ref={this.handleCanvas}/>
            </SafeAreaView>
        );
    }
```

The result on IOS:
![Simulator Screen Shot - iPhone 6 - 2020-02-08 at 12 13 10](https://user-images.githubusercontent.com/43797348/74084151-69318d80-4a6c-11ea-9f74-447d8df46414.png)

The result on Android:
![Screenshot_20200208-121358](https://user-images.githubusercontent.com/43797348/74084165-954d0e80-4a6c-11ea-9557-67e4b8868494.png)

Thanks for your answers

Viktor

**Comment by Gousenfire** [comment]
Same issue as #171
