### ISSUE TITLE
How can i change the width of webview?

### ISSUE THREAD

**Issue by BridgeEast** [iddan/react-native-canvas#18]
I use canvas to show a chart, but the webview width is always 300, can i change it?

**Comment by iddan** [comment]
try ```JavaScript
   ...your component
    handleCanvas = canvas => {
         canvas.width = 400 // <- your desired width
    }
```

**Comment by BridgeEast** [comment]
Will canvas redraw when setState? I don't know how to redraw when data changed

**Comment by iddan** [comment]
This is not done with setState and recommended to start with.

**Comment by iddan** [comment]
@BridgeEast has it solved your problem?

**Comment by BridgeEast** [comment]
@iddan Thanks for your help.
This may not the best solution, but it works for me

```
  // ...your component
  handleCanvas = canvas => {
    this.canvas = canvas;
    canvas.width = 400 // <- It can overwrite the width
  }

  drawCanvas = () => {
    const ctx = this.canvas.getContext('2d');
    ctx.clearRect(0, 0, 400, 300);
    // draw my shape
  }

  // when data updated
  this.setState({
    ...
  }, () => {
    this.drawCanvas();
  });

```
