### ISSUE TITLE
Suggestions for creating a collage

### ISSUE THREAD

**Issue by pythys** [iddan/react-native-canvas#182]
We'd like to create a clothes collage editor which is just a bunch of pictures that the user can manipulate (e.g. zoom in / out, send to front, send to back, and move around the canvas)

Any ideas of the architecture necessary to achieve this? I know I might need some wrapper libraries. Any suggestions for things that work well with react-native-canvas?

I'm specifically interested in knowing how to handle the various events / gestures

**Comment by iddan** [comment]
Gestures should be tracked outside the component with React Native APIs. See: https://reactnative.dev/docs/gesture-responder-system
https://reactnative.dev/docs/panresponder

**Comment by pythys** [comment]
Hello and thank you very much for your feedback. After doing a little bit of research and experimentation, it seems that I need PanResponder in combination with Animated to create the features I need. 

However since I'm dropping down to such low level APIs I am now not sure what is the purpose of using react-native-canvas. Is it to allow multiple images on the same canvas? Isn't that simply possible with a <view></view> holding all the animations with .parallel calls?

**Comment by jules0812** [comment]
@pythys Have you solved this? We're also trying to implement a manipulatable collage feature. If there is a library that can help, please point me to it.

**Comment by pythys** [comment]
Hello. There are no libraries that I am aware of, and the feature was a huge undertaking and it took me a lot of time and effort. The summary of it is as follows

- User PanResponder with Animated for the animations.
- You need to save the state of animations in order to export. This requires knowledge in trig math functions
- Once the collage is complete, you can export it to an image using a library

This feature is so complex that I'm considering publishing to a github project at some point

**Comment by davifalta** [comment]
@pythys any update on that?

**Comment by pythys** [comment]
Nope, when / if I have something cooked up I'll make a post about it
