### ISSUE TITLE
Storing ref with useState leads to Maximum update depth exceeded

### ISSUE THREAD

**Issue by catanon** [iddan/react-native-canvas#195]
```
import React, {useState} from 'react';
import Canvas from "react-native-canvas";

export default function App(){
  const [ref, setRef] = useState(null);
  return (
      <Canvas style={{backgroundColor: "blue"}} ref={canvasRef => {
        if (!canvasRef) return;
        setRef({canvasRef});
      }}/>
  );
}
```
The code produces this error.
![image](https://user-images.githubusercontent.com/49446416/92454415-9b7ab780-f214-11ea-8ef7-1ea6fc8dfca3.png)
![image](https://user-images.githubusercontent.com/49446416/92454495-ad5c5a80-f214-11ea-8e85-6bc096007d35.png)

Somehow, it works if you do `setRef(canvasRef)`. Still, I would prefer to wrap canvas in another object to exposes specific functions.

Should I just use `useRef` instead of ref callback? Does the ref ever change?

I'm running react-native-canves version 0.1.37 on expo's react-native sdk 38.0.2.

**Comment by iddan** [comment]
Setting refs should be don using the `useRef()` hook instead of `useState()`.
```
import React, {useState, useRef} from 'react';
import Canvas from "react-native-canvas";

export default function App(){
  const ref = useRef();
  return (
      <Canvas style={{backgroundColor: "blue"}} ref={ref} />
  );
}
```
Please reopen the issue if it still doesn't work for you

**Comment by catanon** [comment]
Thanks. This way works too.

In the end, what I did is to wrap the ref callback with useCallback(). This prevents the ref callback from being called for every rerender.
