### ISSUE TITLE
TypeError: Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by minhhho2** [iddan/react-native-canvas#196]
I am trying use the library to render a basic canvas with a shape as per example code in the git repo. However, i am getting library errors and cant seem to resolve it. 

I've added the example code to a boiler plate expo project with the minimal typescript setup with no additional code (just the boiler plate project). 

I am getting the following error ...
![image](https://user-images.githubusercontent.com/20630271/97300943-d6a77780-18a2-11eb-8abc-ae35d91090f4.png)

The only custom code that is added is the example code which is added to the TabOneScreen. 
![image](https://user-images.githubusercontent.com/20630271/97301563-a3b1b380-18a3-11eb-8173-054410dd1852.png)

**Comment by GoChartingAdmin** [comment]
Any update on this?

**Comment by iddan** [comment]
Sorry, I could not find time for this yet

**Comment by cre-mer** [comment]
I'm having the same issue. I create a new project with `expo init myProject`.
<img width="415" alt="Bildschirmfoto 2020-12-26 um 09 07 22" src="https://user-images.githubusercontent.com/33655900/103147057-66598d00-4751-11eb-9d90-ef9ef60b80e6.png">

I didn't even add custom code. I only imported Canvas like so `import { Canvas } from 'react-native-canvas';` and it immediately threw the error.

Here is my package.json
`{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "~40.0.0",
    "expo-status-bar": "~1.0.3",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-40.0.1.tar.gz",
    "react-native-canvas": "^0.1.37",
    "react-native-web": "~0.13.12",
    "react-native-webview": "^11.0.2"
  },
  "devDependencies": {
    "@babel/core": "~7.9.0"
  },
  "private": true
}
`

I only added react-native-webview and canvas.

**Comment by iddan** [comment]
Sorry, I could not find time for this yet

**Comment by cre-mer** [comment]
I wanted to contribute and try to fix the problem. But when I git clone and try to install, I get this:
<img width="568" alt="Bildschirmfoto 2020-12-26 um 23 03 24" src="https://user-images.githubusercontent.com/33655900/103159156-2ed8f800-47c6-11eb-8d96-9ee9cff8ab83.png">

**Comment by JosephKastier** [comment]
having the same issue :(

**Comment by PseudoRAM** [comment]
You can temporarily fix it on your local project by updating `Canvas.js` on line 358, replacing `style: _reactNative.ViewPropTypes.style` with `style: _propTypes.default.object` as follows:

![code](https://user-images.githubusercontent.com/6101823/108689899-c8662100-754d-11eb-91fa-a58eb509de9f.png)

**Comment by Oderjunkie** [comment]
having this issue too!

**Comment by yacaeh** [comment]
I heard ViewPropTypes.style is deprecated , so use prop-types instead.
Change this line 
```
style : _reactNative.ViewPropTypes.style,
```
to
```
style:  _propTypes.style,
```

Worked for me with expo SDK 39

**Comment by qurben** [comment]
react-native seems to have removed propTypes from most of their components, in favor of flow/typescript. react-native-web already has removed them (breaking react-native-canvas for web). Maybe it's an idea to also remove propTypes here. At some point react-native might also remove these propTypes.

**Comment by qurben** [comment]
I was stuck for a bit on this, but the solution is actually quite simple. With react-native-web there is no reason to use react-native-webview, and also no reason to use react-native-canvas.

Just using a plain `<canvas>` tag for web works exactly the same as this project does on the other platforms.

```
if (Platform.OS === "web") {
    return <canvas style={{width, height}} ref={handleCanvas} />
}

return (
    <Canvas style={{ width, height }} ref={handleCanvas} />
);
```

The object passed to `ref` is (nearly) the same in both cases.

--- 

It might be a good idea to document that `web` is not supported by this project, or to add this check in the project itself.

**Comment by qurben** [comment]
This is related to #184, in this issue `web` is also used.
