### ISSUE TITLE
Canvas doesn't render in HiDPI 

### ISSUE THREAD

**Issue by BridgeEast** [iddan/react-native-canvas#20]
![image](https://user-images.githubusercontent.com/5134366/29053085-924d9f0a-7c20-11e7-9d80-009a655ac677.png)
red circle looks fuzzy

**Comment by iddan** [comment]
May you please describe the problem you're facing?

**Comment by iddan** [comment]
The circle to the right is an actual image, while there should be a rendered one to the left which apparently it doesn't work. It is a known issue but it has nothing to do with resolution

**Comment by tougbia09** [comment]
nothing to do with resolution ?

shit !!!!!!!!!!!!!!!!! useless library. :-(

**Comment by iddan** [comment]
Hey @tougbia09,

I'm sorry to read that you're frustrated. react-native-canvas is a project by people for free on their free time. We always seek to enhance it and put a lot of effort for this but unfortunately it is still far from perfect.

I do expect comments to use respectful language and users to understand that we're doing our best.

**Comment by iddan** [comment]
I was able to reproduce the resolution problem and plan to fix it in the near future.

**Comment by iddan** [comment]
Fixed at version 0.1.11

**Comment by tougbia09** [comment]
just updated to 0.1.11 and 0.1.14. Then nothing works anymore , Blank canvas. Missed something ?

**Comment by iddan** [comment]
Can you please provide more details?

**Comment by tougbia09** [comment]
`import  React from 'react'; `
`import Canvas,{Image as CanvasImage, Path2D} from 'react-native-canvas';`
`import {StatusBar, StyleSheet, Text, View } from 'react-native';`

` export default class App extends React.Component {`
`          handleCanvas = (canvas) => {`
` canvas.width = 300;`
`  canvas.height = 300;`
 `             const ctx = canvas.getContext('2d');`
`             ctx.fillStyle = 'purple';`
`          ctx.fillRect(0, 0, 100, 100);`
`          }`
`               render() {`
`                           return (`
`                                <Canvas ref={this.handleCanvas}/>`
`                              ) `
`                          }`
`                }`

android 6.0

**Comment by iddan** [comment]
And which device were you trying this on?

**Comment by tougbia09** [comment]
INFINIX  HOT S . But I think that its caused by a weird scroll which appear  ! it behaves like a embded 
 webview.   Have a look  the screenshot  (android emulator samsung s7 -  6.0)

![capture du 2017-09-27 17-37-39](https://user-images.githubusercontent.com/6335902/30929042-ce83787e-a3ac-11e7-874c-4264e9f7a150.png)

**Comment by iddan** [comment]
For me the latest version works well on Android 6.0 emulator (on a Nexus One like emulator). Will try this device.
