### ISSUE TITLE
Canvas clips my drawing to only 300x150

### ISSUE THREAD

**Issue by jc65536** [iddan/react-native-canvas#209]
I'm running this canvas on expo.
My only code:
```
import React, { Component } from 'react';
import { View } from "react-native"
import Canvas from 'react-native-canvas';

export default class App extends Component {

  handleCanvas = (canvas) => {
    const ctx = canvas.getContext('2d');
    ctx.fillStyle = 'purple';
    ctx.fillRect(0, 0, 400, 700);
  }

  render() {
    return (
      <View style={{
        width: 400,
        height: 700
      }}>
        <Canvas ref={this.handleCanvas} style={{
          width: 400,
          height: 700,
          borderWidth: 1,
          borderColor: "red"
        }} width={400} height={700} />
      </View>
    )
  }
}
```

Most of this is copied from the readme, however I do not see a 400x700 rectangle on my screen:
![image](https://media.discordapp.net/attachments/513450269594615841/814396174462484510/Screenshot_20210224-231819.png?width=348&height=754)

The purple rectangle is clipped to a 300x150 rectangle, which I guess is the default canvas dimensions, even though I explicitly set the width and height. It seems that the WebView element within the canvas is set to 300x150.

**Comment by RobinBobin** [comment]
https://github.com/iddan/react-native-canvas/issues/100

**Comment by joonas-yoon** [comment]
thanks, it works good to me
