### ISSUE TITLE
toDataURL

### ISSUE THREAD

**Issue by mcl950121** [iddan/react-native-canvas#218]
Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

**Comment by iddan** [comment]
Can you provide your code please?

**Comment by mcl950121** [comment]
@iddan 
`<View style={{ marginTop: s(20), height: s(208), alignItems: 'center', justifyContent: 'center' }}>
               <Canvas ref={this.handleCanvas} />
</View>`
`handleCanvas = async (canvas) => {
        this.mycanvas = canvas
        const userDetail: any = await simpleStore.get("userDetail")//用户信息
        const ctx = canvas.getContext('2d');

        // 修改画布大小
        canvas.width = 345;
        canvas.height = 208;
        var image = new CanvasImage(canvas, canvas.height, canvas.width);
        image.src = HttpURL.imgurl + userDetail.userCard.cardTemplate
        image.addEventListener('load', async () => {

            ctx.drawImage(image, 0, 0, 345, 208);

            // 绘制文字
            ctx.fillStyle = userDetail.userCard.typeface; //字体颜色
            // 姓名
            ctx.font = '20px Arial';
            ctx.fillText(userDetail.nickname, 20, 30)
            // 部门
            ctx.font = '15px Arial';
            ctx.fillText(userDetail.deptName, 100, 30)
            //职位
            ctx.font = '12px Arial';
            ctx.fillText(userDetail.workPosition || '', 20, 50)
            //号码
            ctx.font = '12px Arial';
            ctx.fillText(userDetail.idNumber || userDetail.phone, 20, 80)
            //邮箱
            ctx.font = '12px Arial';
            ctx.fillText(userDetail.email || '', 20, 100)
            //单位
            ctx.font = '12px Arial';
            ctx.fillText('天津城市规划院', 20, 120)
            //地址
            ctx.font = '12px Arial';
            ctx.fillText('天津市南开区兰坪路18号', 20, 140)

            console.log(111);
            const url = await canvas.toDataURL("image/png");
            canvas.toDataURL("image/png").then((data) => {
                console.log(data);
            })
            console.log(222);       
        });
    }`

**Comment by mcl950121** [comment]
@iddan 
` <View style={{ marginTop: s(20), height: s(208), alignItems: 'center', justifyContent: 'center' }}>
                        <Canvas ref={this.handleCanvas} />
                    </View>
handleCanvas = async (canvas) => {
        this.mycanvas = canvas
        const userDetail: any = await simpleStore.get("userDetail")//用户信息
        const ctx = canvas.getContext('2d');

        // 修改画布大小
        canvas.width = 345;
        canvas.height = 208;

        var image = new CanvasImage(canvas, canvas.height, canvas.width);
        image.src = HttpURL.imgurl + userDetail.userCard.cardTemplate
        // image.src = '../../res/images/bus/huan.png'

        //设置图片跨域访问
        // image.setAttribute("crossOrigin",'Anonymous')
        image.addEventListener('load', async () => {

            ctx.drawImage(image, 0, 0, 345, 208);

            // 绘制文字
            ctx.fillStyle = userDetail.userCard.typeface; //字体颜色
            // 姓名
            ctx.font = '20px Arial';
            ctx.fillText(userDetail.nickname, 20, 30)
            // 部门
            ctx.font = '15px Arial';
            ctx.fillText(userDetail.deptName, 100, 30)
            //职位
            ctx.font = '12px Arial';
            ctx.fillText(userDetail.workPosition || '', 20, 50)
            //号码
            ctx.font = '12px Arial';
            ctx.fillText(userDetail.idNumber || userDetail.phone, 20, 80)
            //邮箱
            ctx.font = '12px Arial';
            ctx.fillText(userDetail.email || '', 20, 100)
            //单位
            ctx.font = '12px Arial';
            ctx.fillText('xxxxxxx', 20, 120)
            //地址
            ctx.font = '12px Arial';
            ctx.fillText('xxxxxxx', 20, 140)

            const url = await canvas.toDataURL("image/png");
            canvas.toDataURL("image/png").then((data) => {
                console.log(data);
            })
            
        });
    }`

**Comment by iddan** [comment]
Seems like the issue has to do with the image cross origin. You can try to set `crossOrigin` property of `img` to "Anonymous"` as described in this article https://konvajs.org/docs/posts/Tainted_Canvas.html

**Comment by mcl950121** [comment]
@iddan  hi, After I add it, the code doesn't go down
`image.crossOrigin = 'Anonymous'
 image.setAttribute("crossOrigin",'Anonymous')`

**Comment by iddan** [comment]
So can the issue be closed?

**Comment by cavasinf** [comment]
Hey @iddan this is still an issue on my side.

When setting crossOrigin, the image is not draw.
Here's a snack : https://snack.expo.dev/@allsoftwareflorian/react-native-canvas---crossorigin

`handleCanvas` is a bit messy, if you have an error reload the app.

**Comment by JRfan123** [comment]
> Hey @iddan this is still an issue on my side.
> 
> When setting crossOrigin, the image is not draw. Here's a snack : https://snack.expo.dev/@allsoftwareflorian/react-native-canvas---crossorigin
> 
> `handleCanvas` is a bit messy, if you have an error reload the app.

I have the same issue
