### ISSUE TITLE
Can't find variable Symbol on Android and logs problem on iOS

### ISSUE THREAD

**Issue by cuongtructran** [iddan/react-native-canvas#22]
Hi iddan,

I tried to install version 0.1.3 but I couldn't get it works on Android. It says "Can't find variable Symbol".

![image](https://user-images.githubusercontent.com/7592921/29033039-e55a4756-7bbd-11e7-8950-7a56190512d2.png)

On iOS, it works but really slow, I checked logs on Xcode and saw that it throws a lot of json logs. Is it possible to remove it?

![image](https://user-images.githubusercontent.com/7592921/29033109-2472c986-7bbe-11e7-901a-8555e1f49155.png)

Thank you and best regards,
Truc.

**Comment by iddan** [comment]
Hey Truc,
As react-native-canvas evolves we are working on enhancing performance but currently it comes second to implementing the whole Context2D interface. And it might be delayed to support React Native's `Animated` API as we believe it can make animations be much easier to render. But we are always open to PRs and ideas about how we can make the component work faster. One of the ideas came to me is using different serialisation than JSON as it pretty slow and heavy.
About Symbol: this is a bug that occurs as I didn't had the time to test the library on older targets. It will be resolved ASAP: it is a small fix so you would be able to continue your development on legacy android soon enough.

Thank you for trying React Native Canvas.
Iddan.

**Comment by iddan** [comment]
Fixed the Symbol issue 0.1.6
