### ISSUE TITLE
Rendering base64 images with react-native-canvas

### ISSUE THREAD

**Issue by nikhilaravi** [iddan/react-native-canvas#23]
I'm trying to render a base64 image on the canvas but keep getting an error: 'TypeError: type error'. 

I'm using the `<Image>' component in react-native and passing this into the drawImage function of the context:

```
  handleCanvas = (canvas) => {
    const ctx = canvas.getContext('2d');
    var img = new Image();
    img.src = `data:image/jpeg;base64,${this.state.imageURI}`
    img.onLoad = function() {
      ctx.drawImage(img, 0, 0, 100, 100);
    }
  }

<Canvas ref={this.handleCanvas}/>
```

**Comment by iddan** [comment]
Will look into it

**Comment by macelii** [comment]
I am experiencing the same issue.
My use case here is to access local image and draw them on the canvas.

**Comment by iddan** [comment]
A little bit busy. PRs are welcome but this won't be handled soon

**Comment by benniao-chen** [comment]
@macelii how to access local image which has a relative path? example: "../../asset/images/a.png"

**Comment by macelii** [comment]
you can read that specific image and encode it into base64.

**Comment by benniao-chen** [comment]
@macelii but camera photo transform to base64, and use this base64 data to draw in canvas, so slow!!!!

**Comment by yogeshR5** [comment]
@iddan  ctx.drawImage()  is not working. when am I using I got the error like
"JSON.stringify cannot serialize cyclic structures"

**Comment by iddan** [comment]
We're using this API in production and it works fine. What is your use-case?

**Comment by cod2017** [comment]
Any update? 
Still not working for base 64 image and for .png image

[  let tempSrc={uri: '........'};
    const image = new Image(this.canvas, 20, 20);
          image.onload = function() {
                this.ctx.beginPath();
                this.ctx.clearRect(0, 0, this.canvas.width, canvas.height);
                this.ctx.drawImage(image, 0, 0, this.canvas.width, this.canvas.height);
                this.ctx.closePath();
                this.ctx.save();
          }
          image.src = tempSrc.uri;
          image.onerror = function() {
      console.log("err")
          };]([url](url))

**Comment by iddan** [comment]
Have you tried using `addEventListener()`?

**Comment by cod2017** [comment]
@iddan Got it working using addEventListener()

**Comment by iddan** [comment]
In the todo there is a task to emit a warning when using image.onload (or making it work). I'd appreciate help with it.
