### ISSUE TITLE
globalCompositionOperation vs. globalCompositeOperation

### ISSUE THREAD

**Issue by RobinBobin** [iddan/react-native-canvas#235]
Your declaration of `CanvasRenderingContext2D` has a field `globalCompositionOperation`, while the actual name is `globalCompositeOperation`.

**Comment by iddan** [comment]
Thank you @RobinBobin

**Comment by iddan** [comment]
Hey, I'm sorry but I couldn't find `globalCompositionOperation` in the code. Can you point me to the wrong code?

**Comment by RobinBobin** [comment]
"react-native-canvas": "^0.1.38"
node_modules/@types/react-native-canvas/index.d.ts
line 45

**Comment by iddan** [comment]
This is an issue with the types library then, not the library itself. You should open an issue in the DefintleyTyped repo

**Comment by RobinBobin** [comment]
Oh, I see.
