### ISSUE TITLE
Not working on production

### ISSUE THREAD

**Issue by shivenj** [iddan/react-native-canvas#24]
Canvas is not viewing when loading from pre bundled source or in production.

**Comment by iddan** [comment]
Thank you for reporting. Can you please give a little more details about the problem you're facing? Can you create a demo project?

**Comment by shivenj** [comment]
When i make a build on ios device . It says loading from pre installed bundles , at that time it canvas doesnot load .

**Comment by shivenj** [comment]
Does it require development server to be live all the time ?

**Comment by shivenj** [comment]
ok here is what i did. i cloned your example . followed Run on Device guide#Building your app for production https://facebook.github.io/react-native/docs/running-on-device.html
![screen shot 2017-07-24 at 11 53 20 am](https://user-images.githubusercontent.com/23523474/29450941-55a06b72-841e-11e7-98f8-5bf3144e9cf2.png)
same when i run normally with my phone and server on different wifi network.
Please tell me which step i am missing.

**Comment by shivenj** [comment]
it was an issue with index.html file. solved it . thanks a lot

**Comment by iddan** [comment]
cool, thank you

**Comment by micahwood** [comment]
How did you solve this issue? It looks like I am having the same thing. When I try to build the application it does not include the index.html file, so it tries to load it from my dev server.

**Comment by iddan** [comment]
When using react-native-canvas you should not provide your own index.html. Can you provide your config?

**Comment by micahwood** [comment]
Right, I am not providing my own index.html file, I am just using this component as is.
When testing my app while running `npm start` I see this output in the logs 
`"http://192.168.1.60:8081/assets/node_modules/react-native-canvas/dist/index.html?platform=android&hash=b8e2fe68dc8d3e09d95158c92a1a1ffe" "Mozilla/5.0 (Linux; Android 7.1.2; Pixel Build/NJH47F; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/60.0.3112.107 Mobile Safari/537.36"`

If I am not running the dev server I get the following error when trying to display a canvas:
`"description": "net::ERR_CONNECTION_REFUSED", "url": "http://192.168.1.60:8081/assets/node_modules/react-native-canvas/dist/index.html?platform=android&hash=b8e2fe68dc8d3e09d95158c92a1a1ffe"`

Which config file are you wanting to see? I haven't modified any of the android config files beyond what is provided when running `react-native init`

**Comment by iddan** [comment]
Why would you turn off the dev server during development?

**Comment by shivenj** [comment]
when you create a production build , android pre fetch all the assets (png,jpg,html) to android assets folder , index.html is also fetched and when you require index.html it is loaded from assets folder. but the path inside the index.html is not found , so you need to copy other files to asset folder

**Comment by iddan** [comment]
Interesting.. Which files should be copied?

**Comment by shivenj** [comment]
all the files as index.html require webview.js and all . See this https://github.com/facebook/react-native/issues/505

**Comment by iddan** [comment]
#14 will handle this

**Comment by shivenj** [comment]
yes as he has copied all content of html into canvas.js

**Comment by iddan** [comment]
indeed :)

**Comment by iddan** [comment]
If you'd like you can help @assertchris finish it

**Comment by assertchris** [comment]
Yeah, sorry about the delay folks. Been preparing for a conference (happening this week) so it's going to be at least another week until I can get that done...

**Comment by iddan** [comment]
0.1.10 should fix this
