### ISSUE TITLE
Please help..

### ISSUE THREAD

**Issue by chukiatt** [iddan/react-native-canvas#282]
Dear sir,

i got this error on running, Please help me to solved.

Require cycle: node_modules\react-native-canvas\dist\Canvas.js -> node_modules\react-native-canvas\dist\Image.js -> node_modules\react-native-canvas\dist\Canvas.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 WARN  Require cycle: node_modules\react-native-canvas\dist\Canvas.js -> node_modules\react-native-canvas\dist\ImageData.js -> node_modules\react-native-canvas\dist\Canvas.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
 LOG  Running "testProject" with {"rootTag":1}

**Comment by nora-soderlund** [comment]
Duplicate of #185.
