### ISSUE TITLE
No license text

### ISSUE THREAD

**Issue by zewt** [iddan/react-native-canvas#289]
package.json says "MIT" so I assume that's what you meant, but there's no actual license file in the repo that I can find.  Could you add a license.txt?

**Comment by iddan** [comment]
Would love a PR 🙏

**Comment by zewt** [comment]
I'm not going to commit a license to somebody else's source code :)  Nobody can legally use your code unless you put a license on it, so I hope you'll fix this.

**Comment by iddan** [comment]
That way or another it's on the record that I approve and merge it :)
I'll put something up

**Comment by iddan** [comment]
Added. Thanks @zewt

**Comment by zewt** [comment]
Thanks.
