### ISSUE TITLE
canvas.toDataURL() returns a transparent image

### ISSUE THREAD

**Issue by trazsam** [iddan/react-native-canvas#29]
Hello, I made a simple canvas which superpose two images and I would like to get the Data64 (or even a jpg file) of it but when I do canvas.toDataURL() the output is:

`Promise {
  "_40": 0,
  "_55": null,
  "_65": 0,
  "_72": null,
}`

Is it normal ?

**Comment by trickeyd** [comment]
Hi, I have had a question about this too. 

These methods return a promise, as you can see, so you would need to wait for it to resolve before the variable can be populated.

However, in my case the promise never actually got resolved. Here is a link to my issue:
[https://github.com/iddan/react-native-canvas/issues/25](url)

If you haven't already try rewriting with async as suggested by @iddan.

**Comment by iddan** [comment]
Hey @trazsam as @trickeyd pointed out this is perfectly normal and you should just `await` for the result.
@trickeyd lately I stabilised the message queue of the webview. can you check if your issue still occurs on the latest version (let's discuss on #25)

**Comment by trickeyd** [comment]
Great thanks, I'll check it out in a bit. :-)

**Comment by trazsam** [comment]
@trickeyd Thanks!

@iddan Thanks also but the output data64 is transparent with `await canvas.toDataURL();` when I try the uri.

Full handleCanvas func : 
`handleCanvas = async (canvas) => {
		canvas.width = 600;
		canvas.height = 800;

		const ctx = canvas.getContext('2d');

		var photo = new CanvasImage(canvas);
		photo.src = 'data:image/jpg;base64,' + this.state.image;
		photo.addEventListener('load', () => {
			ctx.drawImage(photo, 0, 0, 600, 800);
		});

		var watermark = new CanvasImage(canvas);
		watermark.src = '/img/watermark.png';
		watermark.addEventListener('load', () => {
			ctx.drawImage(watermark, 85, 220, 107, 46);
		});

		this.setState({ image_new_uri: await canvas.toDataURL()});

		console.log(this.state.image_new_uri);
	}`

**Comment by iddan** [comment]
Is #14 relevant? Or it is a different problem?

**Comment by trazsam** [comment]
Different as its the output of `canvas.toDataURL()` which give me the transparent data64 image

**Comment by iddan** [comment]
You read the canvas before it was drawn. Your code should be:
```javascript
    handleCanvas = async (canvas) => {
		canvas.width = 600;
		canvas.height = 800;
		const ctx = canvas.getContext('2d');

		var photo = new CanvasImage(canvas);
		photo.src = 'data:image/jpg;base64,' + this.state.image;
		photo.addEventListener('load', () => {
			ctx.drawImage(photo, 0, 0, 600, 800);
		});

		var watermark = new CanvasImage(canvas);
		watermark.src = '/img/watermark.png';
		watermark.addEventListener('load', async () => {
			ctx.drawImage(watermark, 85, 220, 107, 46);
                        const image_new_uri = await canvas.toDataURL()
		        this.setState({ image_new_uri });
                        console.log(image_new_uri)
		});
	}
```

**Comment by HarrYjagariya** [comment]
hi @iddan, I am also facing the same issue, getting the blank image as a response or promise. 

code:- 

handleRedCircle = async canvas => {
    if (canvas != null) {
      canvas.width = 400;
      canvas.height = 400;
      const context = canvas.getContext('2d', {preserveDrawingBuffer: true});
      if (this.state.passObj && this.state?.passObj.alphabets) {
        var images = {};
        {
          this.state.passObj?.alphabets?.map((item, index) => {
            images['img' + index] = new CanvasImage(canvas);
            images['img' + index].src = item.imageUrl;
            images['img' + index].addEventListener('load', async () => {
              return context.drawImage(
                images['img' + index],
                item.xCoordinate / 10,
                item.yCoordinate / 10,
                item.width / 10,
                item.height / 10,
              );
            });
          });
        }
        console.log('url : ', await canvas.toDataURL());
      }
    }
  };
