### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by CusProjects** [iddan/react-native-canvas#30]
`
"react-native-canvas": "^0.1.9",
 "react": "16.0.0-alpha.12",
 "react-native": "0.45.1",
`

![screen shot 2017-09-08 at 3 20 25 pm](https://user-images.githubusercontent.com/14632593/30231683-46826c9e-94a9-11e7-9e57-2056834e0966.png)

**Comment by iddan** [comment]
Hey there, thank you for trying react-native-canvas! react-native-canvas supports react-native version 0.47.0 and after. Can you reproduce the issue after upgrading your react-native package version?

**Comment by CusProjects** [comment]
![screen shot 2017-09-11 at 12 38 48 pm](https://user-images.githubusercontent.com/14632593/30290896-44b2627e-96ee-11e7-9613-2862861e5bd8.png)
 Still an error.

**Comment by iddan** [comment]
0.1.10 should fix this
