### ISSUE TITLE
`clearRect()` crashes in Expo 49

### ISSUE THREAD

**Issue by RobinBobin** [iddan/react-native-canvas#325]
Hi,
I'm using this package with Expo 49.
Every time I use `clearRect()` to clear the canvas I have this exception thrown: `TypeError: this.postMessage is not a function (it is undefined)`. My code:
```
clearRect(0, 0, canvasSize.width, canvasSize.height)
```
`canvasSize.width` and  `canvasSize.height` have valid values.

Any ideas?
Thanks.

**Comment by iddan** [comment]
This should be okay with the latest version.
