### ISSUE TITLE
Animation 

### ISSUE THREAD

**Issue by philipjc-apacio** [iddan/react-native-canvas#33]
I apologise if this is not the place to ask this question, but I am reaching out for some help.

I am trying to animate the shape I draw using your Canvas implementation ( thank you for your creation) but I loose the context of the canvas when I attempt to re-render my component from a state change or a props changes via Redux.

null is not an object (evaluating 'canvas.getContext');

`  handleCanvas = (canvas) => {
    const ctx = canvas.getContext('2d');
    ctx.fillStyle = 'purple';
    ctx.fillRect(0, 0, 100, 100);
  }
 
  render() {
    return (
      <Canvas ref={this.handleCanvas}/>
    )
  }`

Following your example, however I had to bind this.handleCanvas so I could access 'this' from within handleCanvas. When I call a state update or a Redux action from within handleCanvas, re-rendering does not work, this is when I receive the error.

Any help would be greatly appreciated, thanks.

**Comment by iddan** [comment]
Hey there! The common approach in React for this is to save the ref (canvas) as an instance property so:
```javascript
handleCanvas = (canvas) => {
   this.canvas = canvas
   // initial render
}

componentDidUpdate() {
    console.log(this.canvas); // <= the ref
    // cycle animation
}
```

Generally you better use `componentDidUpdate()` or `componentWillUpdate()` for side affects which are not your actual render.

**Comment by philipjc-apacio** [comment]
Thank you, so much for your reply, but I am still unable to get my blue ball to move :)

**Comment by iddan** [comment]
```javascript
let x = this.state.x;
    let y = this.state.y;
    
    this.ctx = this.canvas.getContext('2d');
    this.ctx.beginPath();
    this.ctx.arc(x, y, 10, 0, Math.PI*2);
    this.ctx.fillStyle = "#0095DD";
    this.ctx.fill();
    this.ctx.closePath();
```
should be executed at componentDidUpdate()

**Comment by iddan** [comment]
General tip: you shouldn't bind `handleCanvas()` at `render()` as it will pass a new function prop to `<Canvas />` in each `render()`. Instead use arrow function methods like this:
```javascript
class SnakeComponent extends Component {
    handleCanvas = () => {

    }

    render() {
        return <Canvas ref={this.handleCanvas} />
    }
```
Because `handleCanvas()` is an arrow function `this` is already bounded
