### ISSUE TITLE
Error: Unable to resolve module `react/jsx-runtime` from `node_modules/react-native-canvas/dist/Canvas.js

### ISSUE THREAD

**Issue by ZZongxueyan** [iddan/react-native-canvas#331]
When i install the v0.1.40，my project get the fellow error， but i don't find the react/jsx-runtime on npm 

 Error: Unable to resolve module `react/jsx-runtime` from `node_modules/react-native-canvas/dist/Canvas.js`: react/jsx-runtime could not be found within the project.

**Comment by iddan** [comment]
Can you please see this: https://bobbyhadz.com/blog/react-module-not-found-cant-resolve-react-jsx-runtime

**Comment by iddan** [comment]
Closing for no comment
