### ISSUE TITLE
Does it work in Android

### ISSUE THREAD

**Issue by MidnightJava** [iddan/react-native-canvas#35]
Your simple example works in ios, but in android the rectangle is not rendered. Maybe I'm missing something, but it seems really, really simple. Just doesn't render.

**Comment by iddan** [comment]
Hey, thank you for trying react-native-package and filling this issue.
Can you please provide the Android OS version and which device have you tried this on?

**Comment by MidnightJava** [comment]
Hi thanks for the reply. Therein was the problem. I'm using an Android Simulator, and I had it running Nougat, API level 25. I must have made a change recently inadvertently, because I thought I was running Marshmallow, API level 25, as instructed on the react-native page. The app seemed to be working OK with that OS, until I tried react-native-canvas.

Am I correct that Marshmallow/API 23 is an exact version requirement and not a minimum, for running react-native? If so, then we can close this issue.

**Comment by iddan** [comment]
Can you please try version 0.1.16?

**Comment by MidnightJava** [comment]
I'm at home now, sop testing on a different system (OSX) than when I initially reported (CentOS 7).

With react-native-canvas 0.1.17 my app did not render with a simulator running Android 6/API 23 and a OnePlus Five physical device running Android 7.1.1. I tried two simulators running Marshmllow, a Nexus 7 tablet and a Nexus 5 phone.

With react-native-canvas 0.1.16, all the above rendered successfully, the simulators and the physical device.

**Comment by iddan** [comment]
Okay will continue investigating

**Comment by iddan** [comment]
latest version should fix that
