### ISSUE TITLE
Promise from ctx.getImageData() never returns on Android

### ISSUE THREAD

**Issue by ConorKelleher** [iddan/react-native-canvas#36]
I'm using your package to port existing code for a Node.js program to work on React-Native and it involves drawing an image to the canvas, then reading the pixel data from the canvas. It works on iOS perfectly but when I run it on Android, the promise in ctx.getImageData never returns, so my program's execution halts at the "await", shown below. It's an awkward script but the lines in question are shown below.

            ctx.drawImage(element, 0, 0, width, height);
            ctx.font = font;
            ctx.fillStyle = fontColor;
            ctx.textAlign = textAlign;
            ctx.textBaseline = textBaseline;
            ctx.fillText("Text Overlay", textXCoordinate, textYCoordinate);

            console.log("A")
            imageData = await ctx.getImageData(0, 0, width, height);
            console.log("B")

Both console logs print on iOS, and the image data is accessible but on Android, "A" gets printed and nothing else happens. Because of the structure of your files in the way they inherit methods and properties from webview classes, I'm finding it really hard to debug what's going wrong. Any idea what could be causing this?

**Comment by iddan** [comment]
Interesting. It seems like there are repeating errors for images on Android. Can you please provide the OS version and device you were trying this code on?

**Comment by ConorKelleher** [comment]
I just tested your example project and again, it worked perfectly on iOS but on Android, none of the left images rendered. 

I'm using the latest version of your code.
Android version: 6.0.1
Device: OnePlus One
OS: Cyanogen OS version 13.1.2-ZNH2KAS3P0-bacon
React-native version: 0.48.4
React-native-cli version: 2.0.1

I'll try an android Emulator and see if the same results are observed

**Comment by ConorKelleher** [comment]
Yeah, it's working fine on the emulator for a Nexus 5X

**Comment by iddan** [comment]
Please try version 0.1.16

**Comment by ConorKelleher** [comment]
Sadly updating to the newest code didn't fix my issue. Both my own application and your example one still aren't rendering the canvas on my Android device

**Comment by iddan** [comment]
Can you reproduce the issue on Android Emulator as well?

**Comment by ConorKelleher** [comment]
Not in the one I have installed but I'll try a few others and see if I can find one that fails like my device

**Comment by iddan** [comment]
Amazing, thank you.

**Comment by ConorKelleher** [comment]
Okay so I've a good bit of data to throw your way. I tried running your example project on various emulators and a physical device with different OS versions and resolutions and tried rolling back my installation of react-native-canvas to see how the different devices handle the different versions. I'll give the specifications of the devices first then refer to them by number in the findings.

Physical Device (same as listed in previous comment)
1:
    Device: OnePlus One
    Resolution: 1080 x 1920 xxhdpi
    OS: Cyanogen OS version 13.1.2-ZNH2KAS3P0-bacon
    Target: 6.0.1

Emulators:
2: 
    Device: 5.4 FWVGA
    Resolution: 480 x 854 mdpi
    API: 23
    Target: Android 6.0

3: 
    Device: Galaxy Nexus
    Resolution: 720 x 1280 xhdpi
    API: 25
    Target: Android 7.1.1

4: 
    Device: Nexus 5
    Resolution: 1080 x 1920 xxhdpi
    API: 26
    Target: Android 8.0

Repository Versions tested:
1: 0.1.14 
    Device 1: The canvases don't render at all
    Device 2: The canvases DO render
    Device 3: The canvases don't render at all
    Device 4: The canvases don't render at all
2: 0.1.15
    Device 1: The canvases don't render at all
    Device 2: The canvases DO render
    Device 3: The canvases don't render at all
    Device 4: The canvases don't render at all
3: 0.1.16
    Device 1: The canvases DO render
    Device 2: The canvases DO render
    Device 3: The canvases DO render
    Device 4: The canvases DO render
4: 0.1.17
    Device 1: The canvases don't render at all
    Device 2: The canvases don't render at all
    Device 3: The canvases don't render at all
    Device 4: The canvases don't render at all
5: 0.1.18
    Device 1: The canvases don't render at all
    Device 2: The canvases don't render at all
    Device 3: The canvases don't render at all
    Device 4: The canvases don't render at all

As you can see from the above tests, it seems that prior to release 0.1.16, many devices fail to render the canvases and for some reason, on of the devices (the 5.4 FWVGA) succeeds in rendering them. After 0.1.16, all of my devices, spanning many resolutions and APIs fail to render the canvases. Release 0.1.16 however seems to succeed on 100% of devices (based on a sample size of 4 at least). 

I know you asked me to try 0.1.16 and I thought I had done that but it seems that by the time I got to it, you had released version 0.1.17. As my findings above show, there appears to be regression in that release, with all devices now failing to render the canvases.

I hope this helps you. And hopefully you can recreate my findings and it's not just an issue with my SDK or something

**Comment by iddan** [comment]
This is very helpful and would be reviewed ASAP. Thank you

**Comment by iddan** [comment]
Latest version should fix this

**Comment by ConorKelleher** [comment]
Yep, seems to be working great on 0.1.20

Thanks
