### ISSUE TITLE
Is it possible to pass in an image, and get the RGB back?

### ISSUE THREAD

**Issue by acomito** [iddan/react-native-canvas#38]
Is it possible to pass in an image, and get the RGB back?

**Comment by iddan** [comment]
Hey acomito, thank you for taking interest in react-native-canvas.
Yes, this is possible with `ctx.getImageData()`:
```javascript
handleCanvas = canvas => {
    const ctx = canvas.getContext('2d')
    // draw your content, can be an image
    const { data } = ctx.getImageData(x, y, height, width) // in your case the coordinates you rendered the image
    const rgbMatrix = _.chunk(data, 3) // you can implement chunk yourself, I usually use lodash
}
```
Make sure that if you render content asynchronously (like images) you should `await` for them to render and only then `getImageData`
