### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by atomical** [iddan/react-native-canvas#4]
```
$ npm install react-native-canvas@latest --save
npm ERR! git rev-list -n1 webview-improvements: fatal: ambiguous argument 'webview-improvements': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 webview-improvements: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 webview-improvements: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 webview-improvements: 
npm ERR! Darwin 15.6.0
```

**Comment by aniddan** [comment]
Currently working on a whole revision of the source code. I hope it will fix your issue

**Comment by lavarajallu** [comment]
Same Issue Again

**Comment by aniddan** [comment]
Not yet to push any updates. So it does make sense.

**Comment by lavarajallu** [comment]
Hello @Mr aniddan I want to need Canvas to React native.. Its installation Failure
Please Give any Suggestion

**Comment by lavarajallu** [comment]
Hello @ Iddan Ahahronson  Actually i need to React-native -canvas. But,
its,not working ,Is there any other Possible case right now.

**Comment by aniddan** [comment]
I'll try to make this work ASAP. Right now I can't find an equivalent.

**Comment by lavarajallu** [comment]
Okay Thank u

On Wed, Jan 25, 2017 at 12:44 AM, Iddan Ahahronson <notifications@github.com

**Comment by gen4sp** [comment]
any updates?

**Comment by refikanissa** [comment]
any updates?

**Comment by iddan** [comment]
We're soon to release a new version supporting the latest RN and React versions. Please stay tune

**Comment by iddan** [comment]
The new version has been released
