### ISSUE TITLE
Android Canvas Scroll

### ISSUE THREAD

**Issue by shivenj** [iddan/react-native-canvas#42]
is there any way to disable scroll in android ? i have a canvas which scrolls vertically.

![screenshot_1508752868](https://user-images.githubusercontent.com/23523474/31883369-508b646c-b807-11e7-9f08-45fcb5442500.png)
![screenshot_1508752886](https://user-images.githubusercontent.com/23523474/31883370-50bc1706-b807-11e7-9722-ca8e17774d97.png)

**Comment by iddan** [comment]
it shouldn't be scrollable. Can you provide some details about your usecase?

**Comment by shivenj** [comment]
`<View
								style={{
									position: "absolute",
									top: 0,
									left: 8
								}}
							>
              <ScrollView scrollEnabled={false}> 
								<Canvas 
									key={this.state.reloadCanvas}
									ref={this.handleCanvas}
								/>
               </ScrollView>
							</View>`

`canvas.width = 150
canvas.height = 150`

**Comment by Rossnetherway1020** [comment]
I've got same issue. it shows scroll bar in Android

**Comment by Rossnetherway1020** [comment]
When I didn't set width and height, it cuts off what I drew in canvas.

**Comment by Rossnetherway1020** [comment]
http://prntscr.com/h1a70f

when I double-click canvas component, it becomes

**Comment by shivenj** [comment]
Seems like issue is with autoscale-canvas.js . if i remove autoscale-canvas.js from package the quality degrades but the scroll is solved.
![screenshot from 2017-10-24 15 13 50](https://user-images.githubusercontent.com/23523474/31936008-f26f9962-b8cd-11e7-9214-a2dbd073c8a9.png)

but still can't figure out why canvas shows scroller on page load.
![screenshot from 2017-10-24 15 19 30](https://user-images.githubusercontent.com/23523474/31936243-a4ef1cac-b8ce-11e7-9ce7-bec075ca5bb6.png)

**Comment by ConorKelleher** [comment]
I've also seen this on all my emulators when running the sample project

**Comment by deaknorbert** [comment]
Hey! Can we get a solution for this issue? Thank you very much!

**Comment by iddan** [comment]
Can you please provide some technical details please?

**Comment by deaknorbert** [comment]
There are some printscreens above. Basically, scrollbars are appearing on android.

**Comment by deaknorbert** [comment]
I'm developing on android Nougat with these dependencies

 "react": "16.0.0-beta.5",
    "react-native": "0.49.3",
    "react-native-canvas": "0.1.20",

**Comment by iddan** [comment]
It seems like more of a platform issue than the libraries. Do you know of Android solutions for this?

**Comment by deaknorbert** [comment]
I don't use any WebView. All my code is in react native.

**Comment by iddan** [comment]
Canvas uses it :)

**Comment by deaknorbert** [comment]
I can't make it work unfortunately.

**Comment by iddan** [comment]
What device dimensions are you testing it on?

**Comment by deaknorbert** [comment]
The scrollbars are present on all dimensions no matter on what emulator i'm testing on.  Currently I test it on Nexus 5X API 26 and the examples show scrollbars around them.

**Comment by sahiltaneja07** [comment]
@shivenj how did you draw that circular canvas, basically I need scrollable semi-circular list view in react-native, can you help?

**Comment by Mactub07** [comment]
try to add this string "scrollEnabled: false,"
 http://prntscr.com/hzd8yh

**Comment by iddan** [comment]
Should be resolved by now
