### ISSUE TITLE
width larger than 300?

### ISSUE THREAD

**Issue by Alecell** [iddan/react-native-canvas#44]
Im trying to set the canvas width larger than 300 but I cant, anyway to do this or a allow preview?

**Comment by iddan** [comment]
Can you provide your code please?

**Comment by Benjamin-Dewey** [comment]
Look at this...

[https://github.com/iddan/react-native-canvas/blob/master/src/Canvas.js#L13](url)

The width and height are set to 300 and 150. I can get the Canvas to render at any width and height I want but those properties you see there are still fixed which totally messes up the Canvas's ability to draw correctly

**Comment by iddan** [comment]
You should set the canvas width and height to the ones that you'd like so if you want for example 400 x 500 you would do:
```javascript
    handleCanvas(canvas) {
        canvas.width = 400
        canvas.height = 500
    }
```
