### ISSUE TITLE
canvas.toDataURL() returns image with width 4 times and height 2 times bigger

### ISSUE THREAD

**Issue by ziks21** [iddan/react-native-canvas#48]
Hello. Thank you for this awesome package.

I'm testing getting image data from canvas and i found that image size returned after canvas.toDataURL() call is 4 times in width and 2 times in height bigger than canvas width and height. 
Could you point me what i'm doing wrong please or tell me if it's a bug. My code looks the following way:
```
handleCanvas(canvas) {
       this.canvas = canvas;
        canvas.width = 200;
        canvas.height = 300;
        const context = canvas.getContext('2d');
        const image = new CanvasImage(canvas);
            image.addEventListener('load', () => {
                    context.drawImage(
                        image,
                        0,
                        0
                    );
            });
            image.src = `data:image/jpeg;base64,${this.imageData}`;
        });
    }

...

this.canvas.toDataURL('image/jpeg')
     .then((data) => {
          // By the way here data is wrapped in quotes by some reason, so we need to remove them
          data = data.substring(1);
          data = data.slice(0, -1);

          if (data.indexOf('data:image/jpeg;base64,') > -1) {
               // Removing "data:image/jpeg;base64," for saving into file as base64 data
                data = data.substring(23);
          }
          RNFetchBlob.fs.writeFile(this.path, data, 'base64')
               .then(() => {
                    // Image data saved and has 200x4 pixels width and 300x2 pixels height
               })
     }
```

For saving image react-native-fetch-blob package is used

Thanks in advance

**Comment by iddan** [comment]
It makes sense. To render in high resolution in IOS and Android react-native-canvas multiplies the canvas sizes by the device screen ratio so you must be using a device with a ratio of 2 and that's why you get an image two times larger than you expect.

Is this an issue for you? I think it's fixable but it won't be easy.

Hope that helps. Thanks for using react-native-canvas and reporting this issue.

**Comment by ziks21** [comment]
@iddan Hello again. Thank you for your quick response.

It seems final image is scaled 2 times than canvas size as you said. It's ok for me. But the problem is in another spot. By some reason canvas is resized in width and becomes 2 times bigger that leads to the following results:

This is how image looks in canvas:
<img width="377" alt="screen shot 2017-11-30 at 2 24 51 pm" src="https://user-images.githubusercontent.com/5039404/33430858-af027724-d5da-11e7-8649-e28d1570f452.png">

And this is final image after canvas.toDataURL() call:
<img width="701" alt="screen shot 2017-11-30 at 2 29 29 pm" src="https://user-images.githubusercontent.com/5039404/33430943-05d6b920-d5db-11e7-9cfe-0083e4ad400c.png">

Could you point me how to fix that behaviour please?
Thanks in advance

**Comment by ziks21** [comment]
Ok, i researched the sources and found reason. The problem is that autoScale function is called twice - one time when we set width for canvas and second time when we set height. I fixed locally by removing this.autoScale() call from width and height setters and made this function public by adding it in Canvas.js:

`(0, _webviewBinders.webviewMethods)(['toDataURL', 'autoScale'])`

Then i set width and height of canvas in the following way:
```
this.canvas.width = 600;
this.canvas.height = 800;
this.canvas.autoScale();
```

**Comment by iddan** [comment]
Cool, this is a good lead for a fix

**Comment by spaceemotion** [comment]
Got the same problem today - "fixed" it by cropping the final image.
Any updates on when a fix is in sight? Cheers!

**Comment by iddan** [comment]
Hey there. As I said before PRs are welcome. Currently I don't use this feature with a product and to busy to solve in my (non-existing) free time.

**Comment by iegik** [comment]
```
const handleCanvas = (canvas) => {
    const ctx = canvas.getContext('2d');
    ctx.fillStyle = 'purple';
    console.log(canvas.width, canvas.height)
    ctx.fillRect(0, 0, canvas.width, canvas.height);
};
...
<Canvas ref={handleCanvas} {...{width: 300, height: 400, style: {width: 300, height: 400}}}/>
```

![](https://imgur.com/UMVSDFy.png)

On screenshot you can see, that size of rendered canvas did not match on iOS.

**Comment by iddan** [comment]
The sizes of the canvas should be in IOS twice the actual size to make things complaint with retina. But if I understand correctly it doesn't behave like that on your device.

**Comment by iegik** [comment]
Yes, i think, it abut to boundaries of 300x150... default properties of webView?

**Comment by mohammadFeiz** [comment]
hi , how can i set canvas width and height ? when i set canvas.width = 400 and canvas.height=600 in emulator nothing render and that wall white screen

**Comment by iddan** [comment]
Please open a new issue.
