### ISSUE TITLE
It Was Not Install...

### ISSUE THREAD

**Issue by lavarajallu** [iddan/react-native-canvas#5]
npm install react-native-canvas@latest --save

Issues are:
npm ERR! git rev-list -n1 webview-improvements: fatal: ambiguous argument 'webview-improvements': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 webview-improvements: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 webview-improvements: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 webview-improvements: 
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/6.7.0/bin/node" "/usr/local/bin/npm" "install" "react-native-canvas" "--save"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.7
npm ERR! code 128

npm ERR! Command failed: git rev-list -n1 webview-improvements
npm ERR! fatal: ambiguous argument 'webview-improvements': unknown revision or path not in the working tree.
npm ERR! Use '--' to separate paths from revisions, like this:
npm ERR! 'git <command> [<revision>...] -- [<file>...]'
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/varmabhupatiraju/Desktop/Coordinates/npm-debug.log

**Comment by iddan** [comment]
Just released a new version, it should work now
