### ISSUE TITLE
`Cannot read property constructor of undefined` when drawing image on iOS 9.2

### ISSUE THREAD

**Issue by yuwenhuisama** [iddan/react-native-canvas#50]
![image](https://user-images.githubusercontent.com/7414913/34112490-ad5e40b2-e447-11e7-9d8a-da531530068c.png)

I have tried to draw image on canvas following the code of example, but got errors above.

Then I tried to run `example`'s code but got the same result.

> "react": "16.0.0",
> "react-native": "0.51.0",
> "react-native-canvas": "^0.1.20",

**Comment by iddan** [comment]
Can you provide your code please?

**Comment by yuwenhuisama** [comment]
@iddan it is just the code of [example](https://github.com/iddan/react-native-canvas/tree/master/examples).

**Comment by yuwenhuisama** [comment]
@iddan I have done some experiments and found that if I launch app with `react-native run-ios` command then no error happened, while I launch app with visual studio code's debug button errors will above happened.

**Comment by yuwenhuisama** [comment]
@iddan Well，Maybe I found the reason, which is caused by the system version as follow:

![image](https://user-images.githubusercontent.com/7414913/34127294-87a4c60e-e477-11e7-84be-cea98ae56e60.png)

Left is ios 11.2 (right result) and right is ios 9.2 (wrong result). I guess this is caused by the differrent implements of Webview between those 2 OSs.

**Comment by iddan** [comment]
It might be! I haven't tested iOS 9.. If you discover more please share.

**Comment by iddan** [comment]
Released 0.1.23 which fixes this issue
