### ISSUE TITLE
Waiting for text measurements slowing down draw speed

### ISSUE THREAD

**Issue by spaceemotion** [iddan/react-native-canvas#51]
For a current project of mine I am using the following snippet to draw and wrap Text: https://stackoverflow.com/questions/2936112/text-wrap-in-a-canvas-element/19894149#19894149

The problem with this implementation of the canvas is that getting the text measurements is an asynchronous process. I had to label the function as async and added await labels on the measureText function.

Using this "fix" now gives me quite the paint flashing, each text appearing with a slight delay.

Is there a reason for the asynchronous nature of the method?
Cheers and thanks for the lib!

**Comment by iddan** [comment]
All the methods are asynchronous because they interact with a WebView JS runtime via postMessage-s that's also why they are quite slow.
