### ISSUE TITLE
Render children elements

### ISSUE THREAD

**Issue by egunsoma** [iddan/react-native-canvas#52]
Is it possible to render children elements in `<Canvas>`?

**I want to render TouchableOpacity over the canvas.**
I've tried, but no success, I think it is discarded. Is there any way to do this?
```JSX
<Canvas ... >
  <TouchableOpacity ... >
    <Image ... />
  </TouchableOpacity>
</Canvas>
```

**Comment by iddan** [comment]
Hey there! Thank you for giving react-native-canvas a spin. We are doing something like this:

```JSX
<View>
    <Canvas />
    <TouchableOpacity style={{ position: 'absolute', top: 0, left: 0 }} >
         <Image />
     </TouchableOpacity>
</View>
```
