### ISSUE TITLE
Doesn't work on Android 4 & 5 when used with Expo

### ISSUE THREAD

**Issue by ksedynskyi** [iddan/react-native-canvas#53]
The trouble has been reproduced with your example too (https://www.npmjs.com/package/react-native-canvas).
Please see screenshot below. Digits were added for debugging (as text, before and after "Canvas" object rendering).

![screenshot_2018-01-16-20-38-00-068_com cutanything](https://user-images.githubusercontent.com/35503392/35008464-36bc3cf0-fb05-11e7-8e37-70c3e5d171ca.png)

Used versions:
react@16.2.0
react-native@0.52.0
react-native-canvas@0.1.20

Tested on Android 4.4 and 5.1

Dev machine OS: Linux

**Comment by yogeshR5** [comment]
@iddan even though Android >5 also doesn't work

**Comment by iddan** [comment]
At @kang-health we're using it on production and QA-ed it.
What were you trying to do?

**Comment by yogeshR5** [comment]
@iddan  I 'm trying to implement roulette using react native canvas.but I'm getting the same issue.
what could be the possible solution

**Comment by yogeshR5** [comment]
![screenshot](https://user-images.githubusercontent.com/34572252/35563760-c0645658-05dd-11e8-821a-cc2f00df2422.png)

**Comment by iddan** [comment]
Please send me an email with your code and I'll see if i can help you.

**Comment by yogeshR5** [comment]
@iddan I  sent mail to you.

**Comment by yogeshR5** [comment]
@iddan  what I have to do now?

**Comment by iddan** [comment]
I'll answer your email as soon as possible.

**Comment by yogeshR5** [comment]
@iddan  ????

**Comment by yogeshR5** [comment]
@iddan  Let me know? whether it's possible to implement or not??

**Comment by iddan** [comment]
I think it is, my assumption it has something to do with the JS engine on these versions. Check if webview.js throws exceptions

**Comment by yogeshR5** [comment]
@iddan  Thank you, for your response, and now it's working fine.
Before I used  expo it was not working

**Comment by yogeshR5** [comment]
yeah pretty sure.

**Comment by yogeshR5** [comment]
@iddan  how to use   document.createElement("canvas")  in native ?   and while using this ctx.drawImage(wheelCanvas, -wheelCanvas.width / 2, -wheelCanvas.height / 2)  i got error  "JSON.stringify cannot seralize cyclic structures"

**Comment by yogeshR5** [comment]
@iddan especially  ctx.drawImage() not working..

**Comment by iddan** [comment]
You create a canvas by rendering a `<Canvas />` component. You can't draw a canvas as an image.

**Comment by yogeshR5** [comment]
@iddan  then what can I do ???

**Comment by iddan** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getImageData

**Comment by NN01010101** [comment]
Can confirm, also without the use of Expo. iOS works, Andoird not, same screen as in bug report.

**Comment by iddan** [comment]
Which device and android version have you tested on?

**Comment by NN01010101** [comment]
Samsung GT-N5110 
Android 4.42
react-native: "0.52.2",
react: "16.2.0"

**Comment by iddan** [comment]
Published version 0.1.22 with the incredible fix of @richard-chen-1985 . Is it working now?

**Comment by iddan** [comment]
Closing as no response was given.
