### ISSUE TITLE
react-native-canvas draw arc android not working perfect.

### ISSUE THREAD

**Issue by cooleagle8837** [iddan/react-native-canvas#57]
react-native: 0.47.2
react-native-canvas: 0.1.20

I am drawing the arc using react-native-canvas.
It works fine on iOS but on android it's looking blurring.

Android Screenshot: 
![screenshot_20180425-115534-2](https://user-images.githubusercontent.com/30376020/39233014-3bf0d424-4880-11e8-8be1-9631d1022687.png)

iOS Screenshot:
![img_0179](https://user-images.githubusercontent.com/30376020/39233131-8f5a6e18-4880-11e8-8337-3e24d9a535ba.JPG)

```javascript
handleCanvas = (canvas) => {
    if (canvas) {
      const { percent } = this.props
      const width = this.props.width <= 150 ? this.props.width : 150
      const height = this.props.height <= 150 ? this.props.height : 150
      this.canvas = canvas
      if (Platform.OS === 'ios') {
        this.canvas.width = width
        this.canvas.height = height
      }
      this.ctx = this.canvas.getContext('2d')
      this.draw(percent)
    } else {
      //console.log("Canvas Null")
      return
    }
  }
  draw(percent) {
    const { hslH, lineWidth, step, dark } = this.props
    const width = this.props.width <= 150 ? this.props.width : 150
    const height = this.props.height <= 150 ? this.props.height : 150
    this.ctx.clearRect(0, 0, width, height)
    this.ctx.save()
    const start = -Math.PI/2;
    const end = -Math.PI/2 + 2 * Math.PI * percent / 100;
    const t = lineWidth;
    const radius = (width - t) / 2;
    this.ctx.beginPath()
    this.ctx.arc(width / 2, height / 2, radius, start, 1.5 * Math.PI)
    this.ctx.lineWidth = t
    if (dark) {
      this.ctx.strokeStyle = 'rgba(0, 0, 0, 0.5)'
    } else {
      this.ctx.strokeStyle = 'rgba(100, 100, 100, 0.2)'
    }
    this.ctx.lineCap='round'
    this.ctx.lineJoin = 'round'
    this.ctx.stroke()
    if (percent > 0) {
      const gradient = this.ctx.createLinearGradient(0, width, 0, 0)
      .then(gradient => {
        gradient.addColorStop(0, 'hsl(' + hslH + ', 100%,' + 80 + '%)')
        gradient.addColorStop(1, 'hsl(' + hslH + ', 100%,' + 50 + '%)')
        this.ctx.beginPath()
        this.ctx.arc(width / 2, height / 2, radius, start, end, false)
        this.ctx.strokeStyle = gradient
        this.ctx.lineWidth = t
        this.ctx.lineCap='round'
        this.ctx.lineJoin = 'round'
        this.ctx.stroke()
      })
    }
  }
```
....
```jsx
<Canvas ref={this.handleCanvas}/>
```
....

Anyone has similar experiences?

**Comment by iddan** [comment]
This has to do with the DPI of the device. What is the Android device you're testing on?

**Comment by cooleagle8837** [comment]
I am using Samsung Galaxy S7 and iPhone 7+

**Comment by cooleagle8837** [comment]
But most of the users use

**Comment by iddan** [comment]
Are you running on an emulator or an actual device?

**Comment by iddan** [comment]
Why are you running this code only for iOS?
```javascript
if (Platform.OS === 'ios') {
        this.canvas.width = width
        this.canvas.height = height
}
````

**Comment by cooleagle8837** [comment]
I often had issues when the width & height gets bigger than 150 on iOS, it worked weird so I implemented scaling for iOS components.

**Comment by iddan** [comment]
If you are changing the canvas size you should set it through canvas.width and canvas.height for Android as well.

**Comment by cooleagle8837** [comment]
So you mean, I set canvas.width & canvas.height for Android as well and implement the scaling again for android?
Intersting....
Let me try...

**Comment by iddan** [comment]
You should not do scaling yourself. React Native Canvas auto-scales your canvas dimensions according to the device dimensions.

**Comment by cooleagle8837** [comment]
@iddan , I am a little confused how to deal with it. Can you fix some code snippet?

https://gist.github.com/cooleagle8837/bfc16b4fb061e4fe4af48b521ca3b070

**Comment by iddan** [comment]
Unfortunatley I don't have the time to debug in the moment. Will try to get it later

**Comment by cooleagle8837** [comment]
If you have no time, I will try to debug but actually, I cannot understand what you mean and how I can fix that. I will try various methods you have in mind.
