### ISSUE TITLE
how can refresh the Canvas

### ISSUE THREAD

**Issue by xianliangDev** [iddan/react-native-canvas#63]
how can  refresh the Canvas

**Comment by xianliangDev** [comment]
I use the react-native-canvas to make the picture verifycode, how can i refresh the Canvas when onPress

**Comment by iddan** [comment]
What do you mean by refresh?

**Comment by xianliangDev** [comment]
Mean that change the picture verifycode to a new after onPress the canvas

**Comment by iddan** [comment]
You would only need to clear the canvas and re execute your rendering code. Nothing different from the regular DOM canvas.
