### ISSUE TITLE
Is there a limit to the width and height

### ISSUE THREAD

**Issue by sirlyZ** [iddan/react-native-canvas#64]
`ctx.fillRect(0, 0, 300, 300);`
but it is a rectangle, the height isn't 300

**Comment by olleboll** [comment]
I have this exact issue. I've tried everything (a lot of things.. ok.. some things) to force the canvas to be bigger but it's locked to 150 I think.

Looking at the code in canvas.js this row is there.

`@webviewProperties({width: 300, height: 150})`

Not at all sure if that's whats causing this but it looks conspicuous.

I want a canvas for the entire screen but can't figure out to make it bigger.

**Comment by eduardomunizbarreto** [comment]
The solution of this issue is on #55

**Comment by Harendra1107** [comment]
Hi @iddan, If I'm trying to provide the height/width of the canvas more than 3000 px then it is not returning any base-64 URL, why?
