### ISSUE TITLE
How set local image to image.src?

### ISSUE THREAD

**Issue by jintangWang** [iddan/react-native-canvas#77]
I checked [#60](https://github.com/iddan/react-native-canvas/issues/60) and I used `react-native-fs` instead of `expo` and it's not work. Do you have any suggestions?

**Comment by jintangWang** [comment]
``` js
        for (let i in images) {
            let img = new CanvasImage(global.canvas);
            if (Platform.OS === 'ios') {
                img.src = `${RNFS.MainBundlePath}/assets/${images[i]}`;
            } else {
                img.src = `file:///android_asset/${images[i]}`;
            }
            this._addLoadEvent(img, callback);
        }
```
In addition, You need add assets in directory ios and android .
*android:*
![image](https://user-images.githubusercontent.com/12557847/45811256-35cb5300-bcff-11e8-977a-470585a514fa.png)
*ios:*
![image](https://user-images.githubusercontent.com/12557847/45811279-4380d880-bcff-11e8-9d57-83e735e0f6d2.png)
tip: add assets to ios is need extra operation in Xcode.

**Comment by ShaoGongBra** [comment]
这个方法可以工作

**Comment by ShaoGongBra** [comment]
这个方法可以工作

**Comment by ShaoGongBra** [comment]
用你的方法可以工作，但是要将画布保存成图片的话还是会有跨域问题，将如片转换为base64，就没有这个问题
```
if (Platform.OS === 'android') {
          img.src = 'data:image/png;base64,' + await RNFS.readFileAssets(item.url, 'base64')
        } else {
          img.src = 'data:image/png;base64,' + await RNFS.readFile(`${RNFS.MainBundlePath}/assets/${item.url}`, 'base64')
        }
```
