### ISSUE TITLE
toDataURL promise never resolved nor rejected

### ISSUE THREAD

**Issue by vit24isalomon** [iddan/react-native-canvas#82]
**Issue:** toDataURL promise is not resolved

**Expected behaviour:** toDataURL getting resolved in reasonable time

**What happens:** toDataURL promise remains pending and is never resolved nor rejected

**Platforms:** iOS simulator (11.4) and Android TV (running 5.1.1) (Phillips 43PUS7100/12) (no other devices available for test for now)

**Comment by iddan** [comment]
Great doc! Can you please provide your code?

**Comment by vitsalomonmautilus** [comment]
OK. So I did some more testing and read the doc once again.

The issue arises when I use it as an offscreen canvas
```js
const canvas = new Canvas()
```
I'm not sure where I found this usage (can't find it now) and now I see that it is wrong as the forceUpdate does not run on unmounted component. If mounted it correctly resolves.

Sorry to bother. You can close this issue.
