### ISSUE TITLE
Redraw Canvas when state changes

### ISSUE THREAD

**Issue by Xerus2000** [iddan/react-native-canvas#84]
I have a React Component that changes its state and draws a Canvas based on that state. However, the function given in "ref" is not called upon re-rendering the Component.

**Comment by iddan** [comment]
Makes sense, You should probably call it at `componentDidUpdate()`.

**Comment by Xerus2000** [comment]
What should I call there?

**Comment by iddan** [comment]
https://github.com/iddan/react-native-canvas/issues/76#issuecomment-417915694

**Comment by Xerus2000** [comment]
Thanks, works perfectly! Maybe you should link that in the Readme or smth, seems to me like a fairly common scenario and a pretty unexpected solution.

**Comment by iddan** [comment]
This is more of a general canvas-react issue than actual component issue but you might be right.
