### ISSUE TITLE
How do we refresh a Canvas

### ISSUE THREAD

**Issue by shirishph** [iddan/react-native-canvas#88]
I have this:
```
  handleCanvas = canvas => {
    if(canvas) {
      const ctx = canvas.getContext("2d");
      ctx.fillStyle = "yellow";
      ctx.fillRect(0, 0, canvas.width, canvas.height);
      ctx.beginPath();
      ctx.moveTo(this.state.value, 0);
      ctx.lineTo(canvas.width, canvas.height)
      ctx.stroke();
    }
  };
<Canvas ref={this.handleCanvas} value={this.state.value} width="50" height="150" />
```
The 'this.state.value' is a state variable in the parent component. How can we get the Canvas component to refresh when state changes? Changing value of variable or forceUpdate did not do the trick. I could console.log out messages which indicated that React wants to 'render', but Canvas is not doing anything. Placing a <Text> component showed updates correctly. Or am I doing something fundamentally wrong to achieve refreshing of Canvas?

**Comment by shirishph** [comment]
Correction: Placing a <Text> component showed updates correctly.

**Comment by shirishph** [comment]
Correction again: Placing a simple Text component showed updates correctly.

**Comment by iddan** [comment]
https://github.com/iddan/react-native-canvas/issues/76#issuecomment-417915694

**Comment by shirishph** [comment]
Complete code for reference
```
class MyCanvas extends Canvas {

  constructor(props) {
    super(props)
    this.state = {value: 0}
  }

  handleCanvas = canvas => {
    if(canvas) {
      const ctx = canvas.getContext("2d");
      ctx.fillStyle = "yellow";
      ctx.fillRect(0, 0, canvas.width, canvas.height);
      ctx.beginPath();
      console.log('handleCanvas, value', this.state.value)
      ctx.moveTo(this.state.value, 0);
      ctx.lineTo(canvas.width, canvas.height)
      ctx.stroke();
    }
  };

  componentWillReceiveProps(newProps) {
    let newVal = newProps.value
    this.setState({
      value: newVal
    })
  }

  render () {
    console.log('rendering MyCanvas', this.state.value)
    return (
      <View>
        <Text>VAL: {this.state.value}</Text>
        <Canvas ref={this.handleCanvas} value={this.state.value} width="50" height="150" />
      </View>
    )
  }
}
```
and parent's render has this
`<MyCanvas value={this.state.book}/>`

**Comment by iddan** [comment]
Change `handleCanvas()` to only assign canvas ref to `this` and call `draw()` with your drawing logic. Call `draw()` in `componentDidUpdate()` as well.
