### ISSUE TITLE
Avoid circular imports

### ISSUE THREAD

**Issue by nkovacic** [iddan/react-native-canvas#89]
Require cycle: node_modules\react-native-canvas\dist\Canvas.js -> node_modules\react-native-canvas\dist\Image.js -> node_modules\react-native-canvas\dist\Canvas.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

Can the cycle be removed?

**Comment by iddan** [comment]
Yes, by using an `index.js` that will export the correct classes. Should not be problematic but I would accept a PR doing so.

**Comment by SiJieMa** [comment]
When canvas was synthesized and I returned to the previous page,Errors may occur Image must be initialized with a Canvas instance，Is this the problem of loop import?

**Comment by iddan** [comment]
I don't think so

**Comment by Belval** [comment]
When using Canvas and Image together I get a "Converting circular structure to JSON error". Is this related? How can I fix it?

**Comment by iddan** [comment]
I don't think so. Can you share how are you using them?

**Comment by Belval** [comment]
I import Canvas and Image, then my canvas is created in the render function like this: 

```
import Canvas from 'react-native-canvas';
import Image from 'react-native-canvas';

...

<View>
  <Canvas ref={this.handleCanvas} style={{ border: '1px solid "white"', padding: 15, paddingLeft: 75 }}/>
</View>
```

`handleCanvas` sets an image as the background:

```
handleCanvas = (canvas) => {
        const ctx = canvas.getContext('2d');
        const { imageSrc } = this.state;
        const { imgHeight, imgWidth } = this.props;

        let background = new Image(canvas, imgHeight, imgWidth);
        background.src = `data:image/jpeg,base64,${imageSrc.toString('base64')}`;

        // Image size
        let ratio = background.width / MAX_IM_WIDTH;
        let w = MAX_IM_WIDTH;
        let h = background.height / ratio;

        // Set canvas size
        canvas.width = w;
        canvas.height = h;

        // Draw image in bg
        ctx.drawImage(background, 0, 0, w, h);
    }    
```

Just running this gives me the circular import error.

**Comment by iddan** [comment]
Is it an error or a warning?

**Comment by Belval** [comment]
It was an error, but feel free to ignore the issue as I changed how I draw my images, and it does not use `Image` from `react-native-canvas` anymore.

**Comment by iddan** [comment]
Sorry to read it didn't work for you.

**Comment by robert8888** [comment]
I've got warning cycle references on:
```
Require cycle:
node_modules\react-native-canvas\dist\Canvas.js -> 
node_modules\react-native-canvas\dist\ImageData.js ->
node_modules\react-native-canvas\dist\Canvas.js
```

and 
```
node_modules\react-native-canvas\dist\Canvas.js -> 
node_modules\react-native-canvas\dist\Image.js -> 
node_modules\react-native-canvas\dist\Canvas.js
```

In ImageData and in Image as well you check that given canvas is instanceof Canvas. So you import it and this case circular references. In path2D, you have similar code you get canvas but you don't check is this canvas instanceof Canvas and you don't generate circular references in path2d file.

I should consider remove this condition on begin. I know this is less security code but don't produce wranings.
You can hide some variable on Canvas object and then check that given canvas object have this variable. Or just create function that check that given object have key Canvas variables
