### ISSUE TITLE
Crash on frequent redrawings

### ISSUE THREAD

**Issue by Xerus2000** [iddan/react-native-canvas#91]
I have a canvas that is cleared and has new points drawn on it every second. 
On Android, I end up with a little sad face in the top left of the canvas at some point and on iOS it just stops drawing. There are no errors thrown anywhere.

**Comment by Xerus2000** [comment]
Okay, the issue was apparently a very stupid typo when resizing the canvas:
```
canvas.widget = width
canvas.height = height
```
I wonder though how that crashes it.

**Comment by iddan** [comment]
What do you mean by crush?

**Comment by Xerus2000** [comment]
The sad face I mentioned

**Comment by iddan** [comment]
Oky
