### ISSUE TITLE
Integration with Fabric.js

### ISSUE THREAD

**Issue by Sofianebenabdallah** [iddan/react-native-canvas#93]
How can I import fabricjs in my project to use it with react-native-canvas ?

thank you

**Comment by Tanatcu** [comment]
As i understood after trying to use fabricjs on react native, fabricjs does not work without DOM and BOM (i can be wrong) and fabricjs works only in browsers and nodejs environment (cause nodejs has a library for generating BOM (you can see it in the sources of fabricjs)).

**Comment by iddan** [comment]
If that's the case then unfortunately it will not be possible to integrate Fabric.js. But if it only requires a canvas component like Three.js then it may be possible.

**Comment by iddan** [comment]
Closing this thread as it has gone stale

**Comment by swatiredhu17** [comment]
Does anybody able to use Fabric JS in react native?  Open to suggestions how same can be achieved in react native.
