### ISSUE TITLE
Unable to resize Canvas

### ISSUE THREAD

**Issue by gc1508** [iddan/react-native-canvas#94]
After resizing the canvas, I am unable to draw any element. 
No error is raised, simply nothing appears on the canvas.

```jsx
  render() {
    return (
        <Canvas ref={this.renderCanvas} style={{backgroundColor: "red"}} />
    )
  }

renderCanvas = (canvas) => {

      canvas.width = 400;
      canvas.height = 600;
      
    const context = canvas.getContext('2d');

    context.globalAlpha = 1.0;
    context.fillStyle = 'green';
    context.fillRect(0, 130, 50, 50);
}
```

**Comment by omnikron** [comment]
I've had success with this by 
* using the `ref` callback to store a reference to the canvas on the component
* using `componentDidMount` to resize the canvas initially 
* using `componentDidUpdate` to draw shapes based on `props` 

You could do the drawing in `componentDidMount` as well, if you don't need the canvas to redraw based on user input or whatever. Here's an example of what I mean:

```
import React, { Component } from "react";
import { StyleSheet, Text, View, Dimensions } from "react-native";
import Canvas from "react-native-canvas";

const { width, height } = Dimensions.get('window');

export default class CanvasRectangles extends Component {
  componentDidMount() {
    this.canvas.width = width;
    this.canvas.height = height;
  };

  componentDidUpdate(props) {
    const context = this.canvas.getContext("2d");
    context.clearRect(0, 0, this.canvas.width, this.canvas.height);
    props.rectangles.map(rectangle => {
      const { x, y, height, width } = rectangle;
      context.strokeRect(x, y, width, height);
    });
  }

  render() {
    return (
      <View style={styles.container}>
        <Canvas ref={(canvas: any) => (this.canvas = canvas)}/>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    position: "absolute",
    flex: 1,
    elevation: 1,
  }
});
```

**Comment by gc1508** [comment]
@omnikron Thanks Oli, I am going to give it a try in a little bit. Will let you know how it goes. Cheers.

**Comment by iddan** [comment]
Does it act differently on the web?

**Comment by omnikron** [comment]
@iddan I'm not sure if there is a similar library on web, because you can just render a canvas element normally. My experience of `ref` is that it's normally used to store a reference to a component (e.g. [TextInput](https://facebook.github.io/react-native/docs/direct-manipulation#setnativeprops-to-clear-textinput-value), rather than to perform operations directly, and I have a feeling that changing the state of the DOM in the `ref` callback is what is causing the issues that @gc1508 had.  The approach in my example above works well and might be a more 'react' like way of interacting with the canvas component. Maybe worth adding to the README?

**Comment by gc1508** [comment]
@omnikron @iddan guys, had a bit of luck and actually managed to get a visible canvas after resizing just for a little bit. I am quite surprise. The solution that @omnikron suggested, out of the blue stopped working. 

Hard also to debug what is going wrong. 

My canvas looks like this:
`<Canvas ref={this.handleCanvas} style={{ backgroundColor: "pink" }} />`

In handleCanvas I simply save the canvas for later:
```
handleCanvas = (canvas) => {
    this.canvas = canvas;
  }
```

Resizing and rendering executed as follows:

 componentDidMount() {
    this.canvas.width = width;
    this.canvas.height = height;
  }

  componentDidUpdate() {
    this.renderCanvas();
  }

  renderCanvas = () => {
    const context = this.canvas.getContext('2d');
    context.clearRect(0, 0, this.canvas.width, this.canvas.height);

    this.renderMyImage(context, this.canvas);
  }

and renderMyImage is this:

```
  renderMyImage(context) {
    const image = new CanvasImage(this.canvas);
    image.src = 'https://url..../image.jpg';
    image.addEventListener('load', () => {
      context.drawImage(image, 0, 0);
       ...
     }
   }
```

Any advice? 

Thanks.

**Comment by iddan** [comment]
What's missing is:
```diff
- renderCanvas = () => {
- const context = this.canvas.getContext('2d');
+ renderCanvas = async () => {
+    const context = await this.canvas.getContext('2d');
```

**Comment by iddan** [comment]
I'm closing the issue just because the core question has been answered but please let us know if anything else is not working.

**Comment by gc1508** [comment]
@iddan even after adding await and async as you pointed out, the canvas does not work. I am not entirely sure if I am banging my head against an internal bug or if it is just an error that I am making...

**Comment by gc1508** [comment]
hey @iddan, when does componentDidUpdate get called? 
I am assigning a reference to CANVAS in "handleCanvas", and I have followed the advice provided here moving the actual rendering into componentDidUpdate, but apparently doesnt get called. 
are you able to shed some light pls? 
thanks.

**Comment by iddan** [comment]
Oh wait! you need to call `renerCanvas()` both in `componentDidUpdate()` **and** `componentDidMount()`!

**Comment by edbrito** [comment]
I've been having the same problem. This is my code:

`
import React, { Component } from 'react';
import {
  AppRegistry,
  View,
  PanResponder,
} from 'react-native';

import Canvas, {Image as CanvasImage} from 'react-native-canvas';

export default class ImagePainter extends Component {
  constructor(props) {
    super(props);
  }

  state = {
      image: this.props.image,
      originalImage: this.props.image,
      width: this.props.width,
      height: this.props.height,
      positionX: undefined,
      positionY: undefined,
      canvas: undefined,
  };

  panResponder = PanResponder.create({
    onStartShouldSetPanResponder: (evt, gestureState) => true,
    onStartShouldSetPanResponderCapture: (evt, gestureState) => true,
    onMoveShouldSetPanResponder: (evt, gestureState) => true,
    onMoveShouldSetPanResponderCapture: (evt, gestureState) => true,

    onPanResponderGrant: (evt, gestureState) => {
      const x = Math.floor(evt.nativeEvent.locationX);
      const y = Math.floor(evt.nativeEvent.locationY);
      this.positionX = x;
      this.positionY = y;
    },
    onPanResponderMove: (evt, gestureState) => {
      if(!this.canvas){
        return;
      }

      const x0 = this.positionX;
      const y0 = this.positionY;
      const x1 = Math.floor(evt.nativeEvent.locationX);
      const y1 = Math.floor(evt.nativeEvent.locationY);
      const ctx = this.canvas.getContext('2d');
      ctx.moveTo(x0, y0);
      ctx.lineTo(x1, y1);
      ctx.stroke();
      this.positionX=x1
      this.positionY=y1;
    },
    onPanResponderTerminationRequest: (evt, gestureState) => true,
    onPanResponderRelease: (evt, gestureState) => {
    },
    onPanResponderTerminate: (evt, gestureState) => {
    },
    onShouldBlockNativeResponder: (evt, gestureState) => {
      return true;
    },
  });

  componentDidMount() {
    const canvas = this.canvas;
    if(canvas){
      canvas.width = this.props.width;
      canvas.height = this.props.height;
      this.renderCanvas();
    }
  }

  renderCanvas = async () => {
    if (this.canvas) {
      const canvas = this.canvas;
      const ctx = await canvas.getContext('2d');
      const image = new CanvasImage(canvas, this.props.height, this.props.width);
      image.addEventListener('load', function() {
        ctx.drawImage(image, 0, 0);
      });
      image.addEventListener('error', err => console.log(err))
      image.src = `data:image/jpeg;base64,${this.state.image}`;
    } else {
      console.log('No canvas?')
    }
  }

  componentDidUpdate() {
    this.renderCanvas();
  }

  render() {
    return (
          <View {...this.panResponder.panHandlers} style={{width: this.props.width, height: this.props.height}}>
            <Canvas ref={ canvas => this.canvas = canvas } 
                    style={{borderWidth: 3, borderStyle: 'dashed', width: this.props.width, height: this.props.height}}
                    width={this.props.width}
                    height={this.props.height}
                  />
          </View>
    );
  }
}

AppRegistry.registerComponent('ImagePainter', () => ImagePainter);
`

From what is written here, it should work.

I narrowed down the problem to the resizing. It looks like resizing changes the reference to the canvas?

On my componentDidMount if I leave the canvas.width and height assignments, nothing shows up. If I comment it how, I get a canvas that's too small (300x150px instead of 300x400) but everything works.

I installed react-native-canvas 2 days ago so it should be the most up-to-date...

**Comment by catanon** [comment]
Is the Canvas ref expected to change? Do I need to use callback as ref or just get it once is enough? (Referring to this [answer](https://stackoverflow.com/a/56541442))
