### ISSUE TITLE
Max drawing area seems to be 300x150 on Android

### ISSUE THREAD

**Issue by rogerbright** [iddan/react-native-canvas#95]
On Android: When I create a canvas and draw some lines on it, the canvas itself displays with the correct size and background color, but nothing seems to draw outside the top left 300w x 150h area. Any line that extends past that point gets clipped.

For example:

in render():

      <Canvas style={{backgroundColor: '#202020', height: 300, width: 300 }} 
          key={ cvskey } ref={ (cvs0) => { this.gotcvs(cvs0); } }>
      </Canvas>

in gotcvs(cvs0):

     if (cvs0 == null) return;
     let ctx = cvs0.getContext('2d');
     ctx.strokeStyle = '#a0a0a0';
     ctx.beginPath();
     ctx.moveTo(10, 10);
     ctx.lineTo(250, 250);
     ctx.stroke();
         
Part of the line will be draw, but will be clipped beyond Y values of 150 or so. The canvas just remains blank past that point.

**Comment by iddan** [comment]
Just set the canvas dimensions before rendering:
```javascript
canvas.height = 600;
canvas.width = 1000;
```
