### ISSUE TITLE
Fast Pixel Manipulation 

### ISSUE THREAD

**Issue by Kida007** [iddan/react-native-canvas#97]
was trying to implement a **Scratch Card**  using react-native-canvas.  tried associating PanResponder with Pixel Manipulation ( ctx.getImageData and ctx.putImageData) . but it takes a lot of time to get the Data(Promise).  I think my approach is bad, any fast alternatives for Pixel Manipulation?

**Comment by iddan** [comment]
Currently rendering is not the fastest. If you will share your code maybe I'd be able to help.

**Comment by Kida007** [comment]
creating a rectangle and storing **pixelData** 
```
  async componentDidMount() {
    const canvas = this.canvas.current;
    const ctx = canvas.getContext('2d');
    canvas.height = 300;
    canvas.width = 300;
    ctx.fillStyle = 'green';
    ctx.fillRect(0, 0, 300, 300);

    this.PixelData = await ctx.getImageData(0, 0, 300, 300);
  }

```

Wrapping Canvas with a PanHandler View
```
      <View style={{ padding: 8, backgroundColor: 'pink' }} {...this.panResponder.panHandlers}>
        <Canvas ref={this.canvas} />
      </View>
```

clearing up values of pixels and putting the updated Image data to Canvas.

```
    this.panResponder = PanResponder.create({
      onMoveShouldSetPanResponder: () => true,
      onStartShouldSetPanResponder: () => true,
      onPanResponderMove: (e) => {
        const x = Math.floor(e.nativeEvent.locationX);
        const y = Math.floor(e.nativeEvent.locationY);

        const i = 300 * x + y;

        if (i < 90000) {
          this.PixelData.data[i] = 0;
          this.PixelData.data[i + 1] = 0;
          this.PixelData.data[i + 2] = 0;
          this.PixelData.data[i + 3] = 0;
        }
      },
      onPanResponderRelease: () => {
        const ctx = this.canvas.current.getContext('2d');
        const data = this.PixelData;
        ctx.putImageData(data, 0, 0);
      },
    });
  }

```

2 problems  : 

1) slow 

2) getting error while **putImageData()**

_argument 1 'imagedata' to canvasRenderingContext2d.putimagedata must be an instance of imagedata_

**Comment by Kida007** [comment]
no problem. you can close it if you want!  👍

**Comment by iddan** [comment]
Published an implementation of putImageData
