### ISSUE TITLE
Does not work for Windows UWP

### ISSUE THREAD

**Issue by aikewoody** [iddan/react-native-canvas#98]
Output of `react-native info`:
```
Environment:
  OS: Windows 10
  Node: 10.13.0
  Yarn: 1.12.3
  npm: 6.4.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
```
After installing the plugin and using it as follows:
```
import Canvas from 'react-native-canvas';

  ...

  handleCanvas = canvas => {
    const ctx = canvas.getContext('2d');
    ctx.fillStyle = 'purple';
    ctx.fillRect(0, 0, 100, 100);
  };

  render() {
    return <Canvas ref={this.handleCanvas} />;
  }

  ...

```
The following error appears:
![cc](https://user-images.githubusercontent.com/17004429/49016209-a5d5d980-f185-11e8-852f-124372600dfb.png)

Be aware that this happens when developing for Windows UWP applications in React Native. 
Because there are no other issues like this I suspect that the problem is specific for windows development.

**Comment by iddan** [comment]
Can you please check in the latest published version?

**Comment by iddan** [comment]
Latest version supports UWP
