### ISSUE TITLE
Largest image hide smallest

### ISSUE THREAD

**Issue by theca** [iddan/react-native-canvas#99]
The images that have the largest size always appear above the smallest ones but not in the order I call the images. Because of that I can't put a background since it hides all the other images because its size is higher. how can i fix that?

**Comment by iddan** [comment]
Hello! Thanks for giving React Native Canvas a try. Could you please give a code example?

**Comment by theca** [comment]
hi, i call image with this code:

`function draw(){         

            bg.addEventListener('load', () => {
                 context.drawImage(pipeRight, 0, 0, boxSize, boxSize*6);
                });
            spaceship.addEventListener('load', () => {
                context.drawImage(spaceship, 0, 0, boxSize, boxSize);
            });
        }
        return draw()
`
With the order i should see spaceship. But bg size > spaceship size and and because of that spaceship is hidden by bg. I try bg_size < spaceship_size and spaceship is not hidden by bg. The display does not follow the writing order as it should be.

**Comment by iddan** [comment]
Okay, so this is more to do with general canvas programming than specifically React Native Canvas. The load events of the images occur in parallel which means timing can vary. To solve that you can use promises like so:
```javascript
/**
 * @param image to load
 * @returns {Promise} resolves when image is loaded
 */
const loaded = image =>
  new Promise(resolve => image.addEventListener("load", resolve));

async function draw(){
    await loaded(bg);
    context.drawImage(pipeRight, 0, 0, boxSize, boxSize * 6);
    
    await loaded(spaceship);
    context.drawImage(spaceship, 0, 0, boxSize, boxSize);
}
```

**Comment by iddan** [comment]
If anything else doesn't work for you don't hesitate to ask :)
